76191: Add HelmChart v2 Reference Topic
replicatedhq/replicated-docs pull request #1141
Opened 2023-05-15 18:40 UTC by jonquil2002

SC: https://app.shortcut.com/replicated/story/76191/add-v2-helmchart-reference-topic

2023-05-15 20:19 UTC, jonquil2002 commented on docs/reference/custom-resource-helmchart-v2.mdx
> +* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` fi
@ajp-io @cbodonnell I believe this first applies only to v2, yes?

2023-05-15 20:24 UTC, jonquil2002 commented on docs/reference/custom-resource-helmchart-v2.mdx
> +To ensure the vendor portal includes this conditional `postgresql` resource in the installation file, add the same `postgresql` value to the `builder` key with `enabled` set to `true`:
@ajp-io @cbodonnell In this v2 sentence, I wrote "installation file". In the v1 version, it says "`airgap bundle`. Is it ok to say `installation file` in the v1 version instead of `airgap bundle`? If so, I can share the same content in a partial instead of maintaining two versions of almost identical content.

2023-05-15 20:30 UTC, cbodonnell commented on docs/reference/custom-resource-helmchart-v2.mdx
> +* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` fi
Yup, that's only for v2 and for that particular use-case described.

Related note - If a vendor currently supports airgap installs, they will already have filled out this field, so there would be no additional changes needed on their end.  Additional effort would only be needed for vendors that do not support airgap installs, but do want to support the use-case described here.  They would need to fill out the `builder` field if they haven't already.

2023-05-15 20:40 UTC, cbodonnell commented on docs/reference/custom-resource-helmchart-v2.mdx
> +To ensure the vendor portal includes this conditional `postgresql` resource in the installation file, add the same `postgresql` value to the `builder` key with `enabled` set to `true`:
Interested to hear what @ajp-io thinks here.  In v2, the `builder` field is used by the Vendor Portal (same as v1), but it's also used by the app manager.  Both use those values to template out the Helm chart and find all necessary images.  Maybe we can make the wording more generic so that it's not necessarily referencing the vendor portal or app manager, but gets the point across that `builder` is used to make sure that all conditional resources are included in the installation?

2023-05-15 20:45 UTC, cbodonnell commented on docs/reference/custom-resource-helmchart-v2.mdx
> +### chart.releaseName
`releaseName` is a top-level property of the spec in v2 instead of being nested within `chart` because it's not really part of the "mapping between the data in this definition and the chart archive itself" as we state in the `chart` description.

The example yaml spec above looks correct.

```suggestion
## releaseName
```

2023-05-15 20:48 UTC, cbodonnell commented on docs/partials/helm/_helm-cr-weight.mdx
> +Determines the order to apply charts that have `useHelmInstall: true`. Charts are applied by weight in ascending order, with lower weights applied first. **Supported values:** Positive or negative in
There's a reference to `useHelmInstall: true` here, which wouldn't apply in v2.  Could we re-word it to just reference "native helm" somehow?

2023-05-15 20:49 UTC, cbodonnell commented on docs/partials/helm/_helm-cr-upgrade-flags.mdx
> +Specifies additional flags to pass to the `helm upgrade` command for charts that have `useHelmInstall: true`. These flags are passed in addition to any flags the app manager passes by default. The va
There's a reference to `useHelmInstall: true` here, which wouldn't apply in v2.  Could we re-word it to just reference "native helm" somehow?

2023-05-15 20:50 UTC, jonquil2002 commented on docs/reference/custom-resource-helmchart-v2.mdx
> +* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` fi
I can put some language in about that, I meant to earlier.

2023-05-15 20:51 UTC, jonquil2002 commented on docs/reference/custom-resource-helmchart-v2.mdx
> +To ensure the vendor portal includes this conditional `postgresql` resource in the installation file, add the same `postgresql` value to the `builder` key with `enabled` set to `true`:
Oof, I didn't even see that. I'll just have to make this two different field descriptions instead of sharing a partial.

2023-05-15 20:51 UTC, jonquil2002 commented on docs/partials/helm/_helm-cr-weight.mdx
> +Determines the order to apply charts that have `useHelmInstall: true`. Charts are applied by weight in ascending order, with lower weights applied first. **Supported values:** Positive or negative in
Oof, I didn't even see that. I'll just have to make this two different field descriptions instead of sharing a partial.

2023-05-16 18:40 UTC, jonquil2002 commented on docs/partials/helm/_helm-cr-weight.mdx
> +Determines the order to apply charts that have `useHelmInstall: true`. Charts are applied by weight in ascending order, with lower weights applied first. **Supported values:** Positive or negative in
Yep, did it in the partial for both v1 & v2.

2023-05-16 18:40 UTC, jonquil2002 commented on docs/partials/helm/_helm-cr-upgrade-flags.mdx
> +Specifies additional flags to pass to the `helm upgrade` command for charts that have `useHelmInstall: true`. These flags are passed in addition to any flags the app manager passes by default. The va
Yep, did it in the partial for v1 & v2

2023-05-16 18:41 UTC, jonquil2002 commented on docs/reference/custom-resource-helmchart-v2.mdx
> +To ensure the vendor portal includes this conditional `postgresql` resource in the installation file, add the same `postgresql` value to the `builder` key with `enabled` set to `true`:
Made the changes. PTAL

2023-05-16 18:41 UTC, jonquil2002 commented on docs/reference/custom-resource-helmchart-v2.mdx
> +* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` fi
Made this change. PTAL

2023-05-16 18:42 UTC, jonquil2002 commented on docs/partials/helm/_helm-cr-chart-release-name.mdx
> +> Introduced in Replicated app manager v1.73.0
@ajp-io  Do we need a release number here for v2? Can we delete this language altogether for both v1 & v2?

2023-05-16 18:43 UTC, jonquil2002 commented on docs/partials/helm/_helm-cr-chart-release-name.mdx
> +Defaults to the chart name.
@cbodonnell Seems like this line should be deleted for v2 - yes? Does any other language in this field description need to change for v2?

2023-05-16 19:13 UTC, ajp-io requested changes

2023-05-16 19:13 UTC, ajp-io commented on docs/partials/helm/_helm-cr-chart-release-name.mdx
> +> Introduced in Replicated app manager v1.73.0
I left a similar comment lower down for the v2 resource. We shouldn't mention which version fields were introduced for v2, since they were all released now (whatever our next KOTS version is). It could still be helpful for v1, though those versions are getting older and hopefully people are using sufficiently recent versions. That might be a docs decision.

But for v2, we should just say when the v2 resource was added to KOTS, not individual fields.

2023-05-16 19:13 UTC, ajp-io commented on docs/reference/custom-resource-helmchart-v2.mdx
> +* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` fi
I think we should make it clearer why this is needed. Just a suggestion, doesn't have to be this wording.
```suggestion
* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` field to render the Helm chart with all of the necessary images so that KOTS knows where to pull the images from to push them into the private registry.
```

2023-05-16 19:13 UTC, ajp-io commented on docs/partials/helm/_helm-cr-chart-release-name.mdx
> +Defaults to the chart name.
I might be misunderstanding the question, but I think this statement is still true. It's just that `releaseName` moved from a subfield of `chart` in v1 to a top-level field in v2. But I don't know if I'm missing something.

2023-05-16 19:15 UTC, cbodonnell commented on docs/partials/helm/_helm-cr-chart-release-name.mdx
> +Defaults to the chart name.
> I might be misunderstanding the question, but I think this statement is still true. It's just that `releaseName` moved from a subfield of `chart` in v1 to a top-level field in v2. But I don't know if I'm missing something.

Right, we just moved this field.  The behavior is the same, so I think we can keep the same language too.

2023-05-16 19:24 UTC, cbodonnell commented on docs/reference/custom-resource-helmchart-v2.mdx
> +The HelmChart v2 custom resource supports the native Helm v2 installation. This v2 installation method does a Helm install or upgrade on your Helm chart. Because this method bypasses existing Kustomi
I did some digging late last week and it looks like the annotations are an old thing we have always added in KOTS and are used to identify resources that are managed by KOTS.  However, in this install method, all resources would be managed by Helm, so I'm fairly sure vendors would not need to add annotations.
```suggestion
The HelmChart v2 custom resource supports the native Helm v2 installation. This v2 installation method does a Helm install or upgrade on your Helm chart. Because this method bypasses existing Kustomize logic to rewrite images, inject pull secrets, and add backup labels, you must configure a combination of Replicated and Helm templating for the images, pull secrets, and backup labels.
```

2023-05-16 21:01 UTC, ajp-io requested changes
TBH for the sake of time I just read the parts that I thought were new here—changes to `builder` the intro about v2 installations, etc. I figure the rest of the fields are copy/paste from v1, but let me know if I missed something.

2023-05-17 13:21 UTC, jonquil2002 commented on docs/reference/custom-resource-helmchart-v2.mdx
> +* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` fi
Lol, I thought you were just trying to make that name change happen! I fully supported :)

2023-05-17 14:58 UTC, paigecalvert submitted a review, later dismissed
one comment!

2023-05-17 14:58 UTC, paigecalvert commented on docs/reference/custom-resource-helmchart-v2.mdx
> +* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` fi
I reck'n `disable image push` might be referring to the `--disable-image-push` flag when the user runs the kots install command? Or is it referring to a field somewhere?I think this could be helpful to clarify. When I read it the first time, I thought "when it is not selected _where_?"

2023-05-17 15:05 UTC, ajp-io submitted a review, later dismissed
I made a couple small changes. This is good to me if we add Beta and include the KOTS version this will be released in.

2023-05-17 15:42 UTC, jonquil2002 commented on docs/reference/custom-resource-helmchart-v2.mdx
> +* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` fi
Good call.

@cbodonnell - Pls check and see if the wording for this bullet is now correct? I added the proper flag syntax and added the reference to `kots install`.

If it's correct, please approve the PR. Thank you! :)

2023-05-17 16:01 UTC, cbodonnell commented on docs/reference/custom-resource-helmchart-v2.mdx
> +* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` fi
That is accurate, but it can also be configured in the UI.  My bad for the incorrect wording when I added that to the doc (was going off memory).  Here's what it looks like in the UI:
![Screen Shot 2023-05-17 at 11 48 00 AM](https://github.com/replicatedhq/replicated-docs/assets/17422963/1c5bc089-8efe-4913-8954-bc25b3e5ef13)

So maybe something along the lines of "where the `--disable-image-push` flag is _not_ passed to the `kots install` command or 'Disable Pushing Images to Registry' is _not_ selected"?

2023-05-17 18:20 UTC, jonquil2002 commented on docs/reference/custom-resource-helmchart-v2.mdx
> +* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` fi
@cbodonnell Ah, thanks. Made some changes. What do you think now?

2023-05-17 18:27 UTC, cbodonnell submitted a review, later dismissed

2023-05-17 18:27 UTC, cbodonnell commented on docs/reference/custom-resource-helmchart-v2.mdx
> +* To support online installations that are configured to push and pull from a private registry, where `disable image push` is _not_ selected. You must provide the necessary values in the `builder` fi
Looks good to me!

2023-05-18 16:03 UTC, cbodonnell commented on docs/reference/custom-resource-helmchart-v2.mdx
> +> Introduced in Replicated app manager v1.xx.xx
@jonquil2002 this will be v1.99.0

2023-05-18 16:08 UTC, jonquil2002 commented on docs/reference/custom-resource-helmchart-v2.mdx
> +> Introduced in Replicated app manager v1.xx.xx
Thank you! :)

2023-05-18 16:16 UTC, cbodonnell approved these changes

2023-05-18 17:16 UTC, paigecalvert approved these changes

2023-05-18 22:26 UTC, merged