ci/cd wip
replicatedhq/replicated-docs pull request #1391
Opened 2023-08-21 22:54 UTC by paigecalvert

2023-08-24 17:36 UTC, paigecalvert commented on docs/vendor/ci-overview.md
> +* To help show you are conforming to a secure supply chain, sign all commits and container images. Additionally, provide a verification mechanism for container images.
I pulled this ^ from Ian's best practice's here: https://www.replicated.com/resources/a-model-for-adopting-replicated

I'm not sure if this is worth including in a page about CI/CD or not, or if there's other info that should be included.

2023-08-24 17:43 UTC, paigecalvert commented on docs/vendor/ci-workflows.md
> +## Development Workflow
For each of the steps in both the dev and release workflows, I added info about the CLI command(s) to use and linked to the CLI doc for more info. I also added any requirements and recommendations specific to the step. I also linked to the GitHub Action repo at the top where people can see more complete examples.

I am curious though if there's more that should be added to these steps. For example, the required inputs (like the diagrams in the replicated-actions repo https://github.com/replicatedhq/replicated-actions/tree/main/create-cluster). Or, if there are more genericized examples that could be included that would be helpful for people to see

2023-08-24 17:47 UTC, paigecalvert commented on docs/vendor/ci-workflows.md
> +
Do they need to provide a version label here too when they promote? Or can they just use the release sequence number from the release created in the earlier step?

I know a version label is not required with the promote command, but in the [example release workflow](https://github.com/replicatedhq/replicated-actions/blob/main/example-workflows/release.yaml), it looks like the promote release step include a release-version field:
```
      - name: Promote to Stable channel
        uses: replicatedhq/compatibility-actions/promote-release@v0
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          channel-to: stable
          release-sequence: ${{ needs.push-to-replicated.outputs.release-sequence }}
          release-version: ${{ github.ref_name }}
```

2023-08-24 17:47 UTC, paigecalvert commented on docs/vendor/repository-workflow-and-tagging-releases.md
Removed this topic as it's out of date

2023-08-24 17:48 UTC, paigecalvert commented on docs/vendor/testing-about.md
> +You design your own tests based on your application needs, and then run your tests on the clusters created by the compatibility matrix. For information about test recommendations, see [Test Script Re
^ unrelated minor change to match our xref styles

2023-08-24 17:50 UTC, paigecalvert commented on docs/vendor/tutorial-ci-cd-integration.md
> +# CI/CD Tutorial for KOTS Releases
Change title to call out that this tutorial is KOTS-specific.

I made no other changes here other than minor word changes and using ordered lists rather than bullets. I am not sure if this is still a "tutorial" that we want out there or not.

2023-08-28 14:51 UTC, crdant requested changes

2023-08-28 14:51 UTC, crdant commented on docs/partials/ci-cd/_test-recs.mdx
> +* **Smoke Testing:** Using a single, conformant Kubernetes distribution to test basic functionality of your application with default (or standard) configuration values is a quick way to get feedback
I recommend not only a single conformant distribution, but also that each version they intend to support (1.25, 1.26, 1.27 for example) be included in the smoke test. Our examples in the github actions repo show that as well, I think.

2023-08-28 14:51 UTC, crdant commented on docs/vendor/ci-overview.md
> +* To help show you are conforming to a secure supply chain, sign all commits and container images. Additionally, provide a verification mechanism for container images.
I think at this point most folks are doing some sort of CI/CD, even if they're just discovering they need to add Replicated to it. This best practices guidance is awesome because it can help them improve their entire pipeline, not just do the Replicated part well.

2023-08-28 14:51 UTC, crdant commented on docs/vendor/ci-overview.md
> +For more information, see the [replicated-actions](https://github.com/replicatedhq/replicated-actions/) repository in GitHub.
I think we originally planned on these being more product-ized then they have ended up, so they're in their own repo. It also makes it cleaner for the actions to be in their own repo to conform with how people expect to consume them. I'm partial toward moving the workflows into the example repo, though.

2023-08-28 14:51 UTC, crdant commented on docs/vendor/ci-workflows.md
> +# Recommended CI/CD Workflows
I'd agree.

2023-08-28 14:51 UTC, crdant commented on docs/vendor/ci-workflows.md
> +## Development Workflow
I think the inputs are going to change depending on how the CI/CD tool works so keeping it lighter could make sense. The CLI commands are clear on what they need.

2023-08-28 14:51 UTC, crdant commented on docs/vendor/ci-workflows.md
> +
I would recommend they be explicit about it. I actually just did a bunch of promotion where I left it out and now the version number is confusing me.

2023-08-28 14:51 UTC, crdant commented on docs/vendor/ci-workflows.md
> +
It's probably also worth calling out the release notes.

2023-08-28 16:22 UTC, paigecalvert commented on docs/vendor/ci-workflows.md
> +
Added the following to this section to clarify that they should include the version label here too as well


The following requirements and recommendations apply to release promotion:

* Replicated recommends that you include the `--version` flag with the `release promote` command to explicitly declare the version label for the release. Use the same version label that was used when the release was created as part of [Create a release and promote to a temporary channel](#rel-release) above. Although the `--version` flag is not required, declaring the same release version label during promotion provides additional consistency that makes the releases easier to track. 

   The following requirements and recommendations apply to the version label for the release:
...

2023-08-28 20:17 UTC, merged