Add info about replicated login
replicatedhq/replicated-docs pull request #1463
Opened 2023-09-22 18:38 UTC by paigecalvert

2023-09-22 18:50 UTC, paigecalvert commented on docs/partials/replicated-cli/_sudo-install.mdx
> +:::
I noticed that I wasn't able to install unless I used sudo, so figured this would be helpful

2023-09-22 19:00 UTC, paigecalvert commented on docs/reference/replicated-cli-installing.md
> +      <!-- CHECK ACCURACY OF THESE COMMANDS -->
I am suspicious of these docker/windows commands. The docs currently tell people to run one of these:

- Through a docker container:

      ```
      docker run \
        -e REPLICATED_APP=$APP_NAME \
        -e REPLICATED_API_TOKEN=$TOKEN \
        replicated/vendor-cli --help
      ```

 - On Windows:

      ```
      docker.exe run \
        -e REPLICATED_APP=%APP_NAME% \
        -e REPLICATED_API_TOKEN=%TOKEN% \
        replicated/vendor-cli --help
        ```

But, it seems like instead it should be something like:

```
docker run \
   replicated login --app SLUG --token TOKEN
```

2023-09-22 19:01 UTC, paigecalvert commented on docs/reference/replicated-cli-installing.md
> +## Authenticate with an Application Slug and API Token {#auth}
Moved these steps to a new subheading since they don't really have to do with installing the CLI. It's usage

2023-09-23 14:13 UTC, grantmiller commented on docs/reference/replicated-cli-installing.md
> +      replicated login --app APP_SLUG --token TOKEN
@marccampbell you don't need a toke or an app slug for this command, right? (it creates a token for you and copies it to the right location or something)

@paigecalvert we should probably also make sure we document `replicated logout`

2023-09-23 14:18 UTC, crdant commented on docs/reference/replicated-cli-installing.md
> +      replicated login --app APP_SLUG --token TOKEN
Not @marccampbel but I know the answer. You don't need a token when you use `replicated login`. It grabs an authentication token and creates a config file containing it. If that file is there and the variable isn't set, then it uses that token.

2023-09-23 14:20 UTC, crdant commented on docs/reference/replicated-cli-installing.md
> +      <!-- CHECK ACCURACY OF THESE COMMANDS -->
Either of those would work. The version in the docs is telling docker to set up the environment with the variables set. The option you suggest is telling the command to use a specific app and token without looking at its environment for them.

2023-09-23 14:21 UTC, crdant requested changes
Update to show that the API token and associated setup isn't required when using `replicated login`.

2023-09-25 22:12 UTC, crdant commented on docs/reference/replicated-cli-installing.md
> +      <!-- CHECK ACCURACY OF THESE COMMANDS -->
In the rendered version these commands seem to be cut off

<img width="664" alt="image" src="https://github.com/replicatedhq/replicated-docs/assets/50028/7cf40dee-0a66-4a72-a871-79fbbe260111">

2023-09-26 16:02 UTC, paigecalvert commented on docs/reference/replicated-cli-installing.md
> +  For more information about the `docker run` command, see [docker run](https://docs.docker.com/engine/reference/commandline/run/) in the Docker documentation.
Added link to docker docs for more info

2023-09-26 16:02 UTC, paigecalvert commented on docs/reference/replicated-cli-installing.md
> +1. Authorize the replicated CLI:
Updated these commands so that they use the token env var, and do not include the app env var

2023-09-28 16:37 UTC, merged