WIP add missing cli commands
replicatedhq/replicated-docs pull request #1467
Opened 2023-09-25 23:31 UTC by paigecalvert

2023-09-26 16:59 UTC, paigecalvert commented on docs/reference/replicated-cli-cluster-ls.md
> -```
looks like this had been copied from `channel ls` and never changed

2023-10-02 15:59 UTC, jdewinne requested changes
One small change regarding the openshift example instance type

2023-10-02 15:59 UTC, jdewinne commented on docs/reference/replicated-cli-cluster-versions.md
> +• INSTANCE TYPES: r1.small, r1.medium, r1.large, r1.xlarge, r1.2xlarge
```suggestion
• INSTANCE TYPES: r1.medium, r1.large, r1.xlarge, r1.2xlarge
```

2023-10-02 15:59 UTC, jdewinne commented on docs/reference/replicated-cli-cluster-versions.md
> +• INSTANCE TYPES: r1.small, r1.medium, r1.large, r1.xlarge, r1.2xlarge
Openshift has no instance type `r1.small`

2023-10-02 16:15 UTC, jdewinne approved these changes

2023-10-02 16:24 UTC, merged