HOLD FOR KOTS v1.104.0: Add KOTS/Helm tutorial
replicatedhq/replicated-docs pull request #1537
Opened 2023-10-18 16:29 UTC by paigecalvert

New tutorial added here: https://deploy-preview-1537--replicated-docs-upgrade.netlify.app/vendor/tutorial-kots-helm-setup

2023-10-19 22:35 UTC, ajp-io requested changes

2023-10-19 22:35 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-install-helm.md
> +  On the instance details page, you can see additional insights such the cluster where the application is installed, the version of the Replicated SDK running in the cluster, instance status and upti
```suggestion
  On the instance details page, you can see additional insights such as the cluster where the application is installed, the version of the Replicated SDK running in the cluster, instance status and uptime, and more:
```

2023-10-19 22:35 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-install-kots.md
> +  ```
Should this say example so it's clear you shouldn't just run this? Their app slug will be different.

2023-10-19 22:35 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-install-kots.md
> +  ```
Alternatively, we could add a step where they set an environment variable with their app slug, and then plug that environment variable into all these commands so they can be copied and pasted.

Lower down we run into this issue too because the command is `kubectl kots remove gitea-example --namespace gitea-example --undeploy`, but they have to plug in their own app slug.

2023-10-19 22:35 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-install-kots.md
> +  kubectl kots remove gitea-example --namespace gitea-example --undeploy
As mentioned above, we either need an environment variable for app slug or tell them to plug their app slug in here.

2023-10-19 22:35 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-install-kots.md
> +  On the instance details page, you can see additional insights such the cluster where the application is installed, the version of KOTS running in the cluster, instance status and uptime, and more:
```suggestion
  On the instance details page, you can see additional insights such as the cluster where the application is installed, the version of KOTS running in the cluster, instance status and uptime, and more:
```

2023-10-19 22:35 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +1. In a browser, go to the Gitea URL to confirm that you can see the welcome page for the application:
Gitea actually failed to come up for me. I don't know what went wrong, but this is in the logs. I can run through this again when we make all the changes here—maybe my messing around with a few things caused the issue. Or someone else could test it too.
<img width="1214" alt="Screenshot 2023-10-19 at 4 32 36 PM" src="https://github.com/replicatedhq/replicated-docs/assets/7272359/d16361d6-60b3-4a93-91b9-41827ab90039">

2023-10-19 23:38 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-install-helm.md
> +
We should delete the Helm chart at the end so they're all cleaned up.

2023-10-20 15:28 UTC, paigecalvert commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +1. In a browser, go to the Gitea URL to confirm that you can see the welcome page for the application:
Huh interesting, yeah I'm curious what that could be. I can run through the steps again too

2023-10-20 15:30 UTC, paigecalvert commented on docs/vendor/tutorial-kots-helm-create-app.md
> +# Step 2: Create an Application
Yeah that's a good idea. And this is a shorter procedure than creating the release, so easier to fit in the steps to install/set up the replicated CLI here

2023-10-20 15:34 UTC, paigecalvert commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +   helm install gitea oci://registry-1.docker.io/bitnamicharts/gitea
>It might make sense to just not specify a namespace anywhere here. Then these commands will all use the targeted namespace.

Sounds good 

>We pull the chart and check it out, but then we install it from the internet again (oci://registry-1.docker.io/bitnamicharts/gitea). We might want to do helm install gitea . instead so that we install it from the copy we pulled instead.

Lol, true. I mixed and matched two different sets of instructions

2023-10-20 15:36 UTC, paigecalvert commented on docs/vendor/tutorial-kots-helm-setup.md
> +  :::
Yeah for sure, I think that would be helpful to include

2023-10-20 17:37 UTC, paigecalvert commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +1. In a browser, go to the Gitea URL to confirm that you can see the welcome page for the application:
I had been testing this with clusters that I created with the compatibility matrix, and never had issue. And then when I tested it just now with a cluster that I created in the Google cloud console, I wasn't able to access the Gitea app either at the external IP. So I wonder if it has to do with some default settings in GKE? I didn't see anything in the networking section that immediately jumped out to me though

2023-10-23 14:47 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +1. In a browser, go to the Gitea URL to confirm that you can see the welcome page for the application:
It probably does have to do with GKE. I'll test out the wordpress chart as soon as I can. I also have a couple new thoughts about the namespace that I'm going to put in a new review now.

2023-10-23 14:54 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +   helm install gitea .
On second thought, since we're using their existing cluster, I think it's good to put our stuff in a dedicated namespace so it's totally separated from anything they're already doing in that cluster.

That involves setting the namespace and telling Helm to create it (because it likely doesn't exist yet), and then cleaning up that namespace at the end. I've included suggestions here.

Then we should reference that namespace in all necessary kubectl commands.
```suggestion
   helm install gitea . -n gitea --create-namespace
```

2023-10-23 14:54 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +   export SERVICE_IP=$(kubectl get svc --namespace default gitea --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
```suggestion
   export SERVICE_IP=$(kubectl get svc --namespace gitea gitea --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
```

2023-10-23 14:54 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +   echo Password: $(kubectl get secret --namespace default gitea -o jsonpath="{.data.admin-password}" | base64 -d)
```suggestion
   echo Password: $(kubectl get secret --namespace gitea gitea -o jsonpath="{.data.admin-password}" | base64 -d)
```

2023-10-23 14:54 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +   kubectl get svc gitea --watch
```suggestion
   kubectl get svc gitea --namespace gitea --watch
```

2023-10-23 14:54 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +   export SERVICE_IP=$(kubectl get svc gitea --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
```suggestion
   export SERVICE_IP=$(kubectl get svc gitea --namespace gitea --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
```

2023-10-23 14:54 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +   helm delete gitea
```suggestion
   helm delete gitea -n gitea
```

2023-10-23 14:54 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-get-chart.md
> +
I don't know how to put a code block in a suggestion since a suggestion is already a code block, but we should delete the namespace to clean up when finished.

1. Delete the `gitea` namespace Helm created:

```
helm delete namespace gitea
```

2023-10-23 15:29 UTC, ajp-io commented
@paigecalvert I just resolved a bunch of suggestions I had opened. I realized I was thinking about something wrong. I need to go through the tutorial again using wordpress and I'll let you know if it works and make any last suggestions.

2023-10-24 19:06 UTC, paigecalvert commented on docs/vendor/tutorial-kots-helm-install-helm.md
> +1. Run the commands in the provided in the **Helm install instructions** dialog to log in to the registry and install the Helm chart.
Updated this to have them create a namespace before running these commands per https://replicated.slack.com/archives/C02BPJQQP28/p1698159474070909?thread_ts=1698074900.265389&cid=C02BPJQQP28

2023-11-06 19:44 UTC, ajp-io reviewed
Really good job! I like this tutorial a lot.

2023-11-06 19:44 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-create-app.md
> +   replicated create app Gitea
```suggestion
   replicated app create Gitea
```

2023-11-06 19:44 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-package-chart.md
> +   <DependencyYaml/>
Can be done separately, but we should update to beta.12 now that we're there.

2023-11-06 19:44 UTC, ajp-io commented on docs/vendor/tutorial-kots-helm-install-helm.md
> +1. After an external IP address is available for the `gitea` LoadBalancer service, follow the instructions in the output of the installation command to get the Gitea URL and then confirm that you can
Not sure it matters, but the URL fails for me a couple times and then it works. So I have to refresh a few times.

2023-11-06 20:27 UTC, paigecalvert commented on docs/vendor/tutorial-kots-helm-install-helm.md
> +1. After an external IP address is available for the `gitea` LoadBalancer service, follow the instructions in the output of the installation command to get the Gitea URL and then confirm that you can
Interesting, I wonder if it's possible that the external IP address is available for the `gitea` LoadBalancer service before the deployment is ready, and so the URL isn't working until the deployment is fully ready. In a separate PR, I'll run through this again and see if it's more accurate to tell people to watch the deployment rather than watch the LB service

2023-11-06 20:29 UTC, paigecalvert commented on docs/vendor/tutorial-kots-helm-package-chart.md
> +   <DependencyYaml/>
done, good call

2023-11-06 20:30 UTC, merged