44393 adds semver topics
replicatedhq/replicated-docs pull request #200
Opened 2022-03-08 20:18 UTC by paigecalvert

2022-03-08 20:58 UTC, ajp-io requested changes

2022-03-08 20:58 UTC, ajp-io commented on docs/vendor/releases-semantic-versioning.md
> +For applications created before February 23, 2022, semantic versioning is disabled by default on new and existing channels.
The new channels part is actually true for all applications regardless of when they were created. Any new channel doesn't default to having semver enabled.

2022-03-08 20:58 UTC, ajp-io commented on docs/vendor/releases-semantic-versioning.md
> +For channels with semantic versioning, the Replicated admin console sequences releases by their semantic versions instead of their creation dates. The admin console does not sort any releases already
IMO it's important to say that semantic versioning is enabled, since a vendor could use semantic versioning for their version labels, but they still wouldn't get these benefits/behaviors unless they enabled our semantic versioning support for the channel.
```suggestion
For channels with semantic versioning enabled, the Replicated admin console sequences releases by their semantic versions instead of their creation dates. The admin console does not sort any releases already promoted to the channel that do not use a valid semantic version.
```

2022-03-08 20:58 UTC, ajp-io commented on docs/vendor/releases-semantic-versioning.md
> +The admin console sorts releases with semantic versions starting with the earliest version and proceeding to the latest.
This was only added for the case where some versions don't use semantic versioning. I don't think this makes sense when stated more generally on its own like this. This is just in relation to how we sort the versions if some aren't semantic versions.

2022-03-08 21:35 UTC, jonquil2002 commented on docs/reference/replicated-cli-channel-disable-semver.md
> +Disable semantic versioning for a channel.
Disable versus disables?

2022-03-08 21:36 UTC, jonquil2002 submitted a review, later dismissed
One minor thought/question. But LGTM

2022-03-08 21:57 UTC, paigecalvert commented on docs/vendor/releases-semantic-versioning.md
> +The admin console sorts releases with semantic versions starting with the earliest version and proceeding to the latest.
@ajp-io re-reading this blurb and the content on the corresponding kots.io topic, it looks like this blurb does state both cases: 1) what does the admin console do when semver is enabled, and 2) what does it do when there are some versions that don't have valid semver on the channel. ("The admin console does not sort any releases already promoted to the channel that do not use a valid semantic version.")

Could you clarify the specific suggested change or missing piece? Or, was this concern maybe already helped by your above commit to add the word "enabled" after "For channels with semantic versioning"? Thank you!

2022-03-08 21:59 UTC, paigecalvert commented on docs/vendor/releases-semantic-versioning.md
> +For applications created before February 23, 2022, semantic versioning is disabled by default on new and existing channels.
Ah great catch, thanks for the clarification.

2022-03-08 22:02 UTC, paigecalvert commented on docs/vendor/releases-semantic-versioning.md
> +The admin console sorts releases with semantic versions starting with the earliest version and proceeding to the latest.
One other thought is that I could change "For channels with semantic versioning enabled, the Replicated admin console sequences releases by their semantic versions instead of their creation dates." to "For channels with semantic versioning enabled, the Replicated admin console sequences releases **with valid semantic versions** by their ~~semantic versions~~ instead of their creation dates."

Does that perhaps address the concern?

2022-03-08 22:18 UTC, jonquil2002 approved these changes
lgtm

2022-03-08 22:19 UTC, ajp-io commented on docs/vendor/releases-semantic-versioning.md
> +The admin console sorts releases with semantic versions starting with the earliest version and proceeding to the latest.
I was referring to this sentence.
>The admin console sorts releases with semantic versions starting with the earliest version and proceeding to the latest.

The earliest to latest part is just in relation to how releases are sorted if non-valid semvers are present as well. In that case (like the example I provided with abc and xyz labels), it sorts from the earliest to the latest. So this really goes with the example that is just below it.

2022-03-08 22:20 UTC, ajp-io commented on docs/vendor/releases-semantic-versioning.md
> +The admin console sorts releases with semantic versions starting with the earliest version and proceeding to the latest.
These comments aren't always clear which line they refer to since they show preceding lines for context!

2022-03-08 22:32 UTC, paigecalvert commented on docs/vendor/releases-semantic-versioning.md
> +The admin console sorts releases with semantic versions starting with the earliest version and proceeding to the latest.
Ahh, I see! So, you were hoping for the example to be part of the same paragraph as "The admin console sorts releases with semantic versions starting with the earliest ..." rather than there being a carriage return between them. I can definitely do that. 

I generally break up longer paragraphs to improve readability (our brains tend to struggle more when processing chunks of text). But I can certainly see how it wouldn't be quite as clear that the example corresponds specifically to the case described that sentence with a carriage return breaking them up.

2022-03-08 22:42 UTC, ajp-io commented on docs/vendor/releases-semantic-versioning.md
> +For example, assume that you promote these releases in the following order to a channel: 1.0.0, abc, 0.1.0, xyz, and 2.0.0. Then, you enable semantic versioning on that channel. The admin console wou
```suggestion
If releases that do not use a valid semantic version are already promoted to a channel, the admin console sorts the releases that do have semantic versions starting with the earliest version and proceeding to the latest.

For example, assume that you promote these releases in the following order to a channel: 1.0.0, abc, 0.1.0, xyz, and 2.0.0. Then, you enable semantic versioning on that channel. The admin console would sequence the version history as follows for the channel: 0.1.0, 1.0.0, abc, xyz, 2.0.0.
```

2022-03-08 22:43 UTC, ajp-io commented on docs/vendor/releases-semantic-versioning.md
> +The admin console sorts releases with semantic versions starting with the earliest version and proceeding to the latest.
Yeah, removing the carriage return is one option. Or we can clarify the case for which this sentence applies. I added another suggestion below that does that, and you can choose which style is preferable.

2022-03-08 22:58 UTC, paigecalvert commented on docs/vendor/releases-semantic-versioning.md
> +For example, assume that you promote these releases in the following order to a channel: 1.0.0, abc, 0.1.0, xyz, and 2.0.0. Then, you enable semantic versioning on that channel. The admin console wou
This commit got outdated, but added it in as part of https://github.com/replicatedhq/replicated-docs/pull/200/commits/72159fdca811e9d148cb7ba840d1a045373f517d

2022-03-09 00:08 UTC, ajp-io commented on docs/vendor/releases-semantic-versioning.md
> +For channels with semantic versioning, the Replicated admin console sequences releases by their semantic versions instead of their creation dates. The admin console does not sort any releases already
I'm going to commit this suggestion since it was marked as resolved but wasn't actually committed. I think maybe it was committed before but got overwritten in subsequent changes.

2022-03-09 00:24 UTC, ajp-io approved these changes

2022-03-09 00:24 UTC, merged