add preflight check docs
replicatedhq/replicated-docs pull request #212
Opened 2022-03-10 15:55 UTC by pavansokkenagaraj

2022-03-10 18:21 UTC, JustinN-Replicated commented
@jonquil2002 likely not ready yet, but I made a few commits. Likely we will need to clean up the original commit since there is too much content in one specific enterprise focused area; having said that though, I did notice that [this page](https://docs.replicated.com/enterprise/installing-existing-cluster-online#pass-preflight-checks) seems to only be the one that alludes to preflight checks for enterprises which seems odd. Likely better for us to hop on a zoom and discuss.

2022-03-10 19:10 UTC, jonquil2002 commented
@JustinN-Replicated @pavansokkenagaraj  Please lmk if I added the correct CLI to two of the topics (I clarified with kots CLI). We have more than on CLI so we always need to specify which one.

Also, the naming of the CLIs are replicated CLI and kots CLI, though the commands are `kots` and `replicated`. Just giving context on when to use the backticks.

Please lmk when you're ready for another review or if you disagree with my changes. I'll give a final approval after you let me know that the content is stable.

2022-03-10 19:27 UTC, JustinN-Replicated commented
Oddly enough, it is troubleshoot cli. Here is a picture of the screen:
![image](https://user-images.githubusercontent.com/84782406/157739625-ba10456c-8938-4a0f-a0d2-2a29f8054a8e.png)

2022-03-10 19:28 UTC, JustinN-Replicated commented
Sorry I probably should've provided this reference as well: https://troubleshoot.sh/docs/#installation

2022-03-10 20:12 UTC, ajp-io requested changes

2022-03-10 20:12 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-online.md
> +When strict preflight checks are used, the application deployment is blocked if the vendor-specified requirements are not met. The deployment fails until the requirements are resolved. When strict pr
As an uneducated user, I might think this means you can mark all preflights in total as strict, when in reality you mark individual preflights as strict. This part could be clarified to say that individual preflights can be strict, and it is only those failures that block the deployment. If non-strict ones fail but the strict ones pass, then the deployment can proceed.

2022-03-10 20:12 UTC, ajp-io commented on docs/enterprise/updating-apps.md
> +The installer may elect to ignore these failures and proceed with the upgrade. If any `strict` preflight checks are configured and the check has a `fail` outcome, the release cannot be deployed. For
Instead of appending this, we should amend the original wording. Else we say, "preflight failures don't block the upgrade" and then say, "but actually strict ones do."

2022-03-10 20:12 UTC, ajp-io commented on docs/reference/custom-resource-application.md
> +During minimal role-based access control (RBAC) installations where a `strict` [preflight](../vendor/preflight-support-bundle-creating#creating-preflight-checks) is specified, you can use the kots CL
Is this specific to strict preflights? I thought with minimal RBAC the cluster-scoped preflights would fail and you would have the use the CLI, even if no strict preflights exist. But I could be wrong; I'm not an expert on minimal RBAC.

2022-03-10 20:12 UTC, ajp-io commented on docs/reference/kots-cli-set-config.md
> +Note: If any [`strict preflights`](../docs/vendor/preflight-support-bundle-creating.md) are configured, the `--skip-preflights` flag will not be honored since preflight checks must be ran and contain
```suggestion
Note: If any [`strict preflights`](../docs/vendor/preflight-support-bundle-creating.md) are configured, the `--skip-preflights` flag will not be honored since preflight checks must run and contain no failures before the application can be deployed. 
```

2022-03-10 20:12 UTC, ajp-io commented on docs/reference/kots-cli-upload.md
> +Note: If any [`strict preflights`](../docs/vendor/preflight-support-bundle-creating.md) are configured, the `--skip-preflights` flag will not be honored since preflight checks must be ran and contain
```suggestion
Note: If any [`strict preflights`](../docs/vendor/preflight-support-bundle-creating.md) are configured, the `--skip-preflights` flag will not be honored since preflight checks must run and contain no failures before the application can be deployed. 
```

2022-03-10 20:12 UTC, ajp-io commented on docs/reference/kots-cli-upstream-upgrade.md
> +Note: If any [`strict preflights`](../docs/vendor/preflight-support-bundle-creating.md) are configured, the `--skip-preflights` flag will not be honored since preflight checks must be ran and contain
```suggestion
Note: If any [`strict preflights`](../docs/vendor/preflight-support-bundle-creating.md) are configured, the `--skip-preflights` flag will not be honored since preflight checks must run and contain no failures before the application can be deployed. 
```

2022-03-10 20:12 UTC, ajp-io commented on docs/vendor/preflight-support-bundle-creating.md
> +* **Strict preflight checks**: When an analyzer is marked as [`strict`](https://troubleshoot.sh/docs/analyze/#strict), the deployment of the release is blocked for `fail` outcomes. This feature can b
```suggestion
* **Strict preflight checks**: When an analyzer is marked as [`strict`](https://troubleshoot.sh/docs/analyze/#strict), any `fail` outcomes for that analyzer will block the deployment of the release. This can be used to prevent users from deploying a release until vendor-specified requirements are met. When configuring `strict` preflight checks, vendors should consider the app manager [cluster privileges](../reference/custom-resource-application#requireminimalrbacprivileges). 
```

2022-03-10 20:16 UTC, JustinN-Replicated commented on docs/enterprise/installing-existing-cluster-online.md
> +For automatic application deployments, the results of the preflight are evaluated before deploying the application. If a strict preflight check fails, then the automatic deployment does not deploy. Y
In discussing with @pavansokkenagaraj, this will be redundant once orange releases [sc-44113](https://app.shortcut.com/replicated/story/44113/preflights-should-run-and-be-respected-prior-to-automatically-deploying-updates) - is that expected to be in this same kots release? If so then we can remove this (I think yes but am unsure)

2022-03-10 20:17 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-online.md
> +For automatic application deployments, the results of the preflight are evaluated before deploying the application. If a strict preflight check fails, then the automatic deployment does not deploy. Y
It's in development this week. I'd remove this and Orange will doc the automatic upgrades part.

2022-03-10 21:08 UTC, JustinN-Replicated commented on docs/enterprise/installing-existing-cluster-online.md
> +For automatic application deployments, the results of the preflight are evaluated before deploying the application. If a strict preflight check fails, then the automatic deployment does not deploy. Y
Ok, sounds good. Will remove the below and resolve this thread
>For automatic application deployments, the results of the preflight are evaluated before deploying the application. If a strict preflight check fails, then the automatic deployment does not deploy. You must resolve this failure and manually deploy the version.

2022-03-10 21:11 UTC, JustinN-Replicated commented on docs/enterprise/installing-existing-cluster-online.md
> +When strict preflight checks are used, the application deployment is blocked if the vendor-specified requirements are not met. The deployment fails until the requirements are resolved. When strict pr
I adjusted the wording here to be a bit more explicit about how each check could or could not be set to strict

2022-03-10 21:11 UTC, JustinN-Replicated commented on docs/enterprise/updating-apps.md
> +The installer may elect to ignore these failures and proceed with the upgrade. If any `strict` preflight checks are configured and the check has a `fail` outcome, the release cannot be deployed. For
I made some adjustments to this section

2022-03-10 21:12 UTC, JustinN-Replicated commented on docs/enterprise/installing-existing-cluster-online.md
> +### Resolve strict preflight checks
made this adjustment

2022-03-10 23:09 UTC, ajp-io commented on docs/reference/custom-resource-application.md
> +During minimal role-based access control (RBAC) installations where a `strict` [preflight](../vendor/preflight-support-bundle-creating#creating-preflight-checks) is specified, you can use the kots CL
Yeah, I just mean that this
> During minimal role-based access control (RBAC) installations where a `strict` [preflight](../vendor/preflight-support-bundle-creating#creating-preflight-checks) is specified, you can use the kots CLI to run preflight checks and upload the results.

sounds like it only does that when strict preflights exist. But you can use the kots CLI to run preflights and upload the results anytime, and you'll have to for minimal RBAC.

2022-03-10 23:14 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-airgapped.md
> +#### Resolve strict preflight checks
I think it makes sense for the pass preflight header to be at the same level as uploading the air gap bundle, but right now it's nested inside of it.
```suggestion
## Pass preflight checks

The app manager runs preflight checks (conformance tests) against the target namespace and cluster to ensure that the environment meets the minimum requirements to support the application.

![Preflight Checks](/images/preflight-checks.png)

### Resolve strict preflight checks
```

2022-03-10 23:26 UTC, ajp-io reviewed
Made a few more comments after my prior were resolved.

2022-03-10 23:26 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-airgapped.md
> +When one or more strict preflight checks are present, the application deployment is blocked until these strict checks are ran. Strict preflight checks must not contain failures and will block the rel
```suggestion
When one or more strict preflight checks are present, the application deployment is blocked until these strict checks run. Strict preflight checks must not contain failures and will block the release from being deployed until the failure is resolved. A vendor may specify strict preflight checks to help enforce that specific requirements are met before the application can be deployed. 
```

2022-03-10 23:26 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-airgapped.md
> +When installing with [minimal role-based access control (RBAC)](../reference/custom-resource-application#requireminimalrbacprivileges), the app manager recognizes if the preflight checks have failed
```suggestion
When installing with [minimal role-based access control (RBAC)](../reference/custom-resource-application#requireminimalrbacprivileges), the app manager recognizes if the preflight checks have failed due to insufficient privilege. When this occurs, a `kubectl preflight` command is displayed that can be run manually in the cluster to run the preflight checks. When the command runs and completes, the results are automatically uploaded to the app manager.
```

2022-03-10 23:26 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-automation.md
> +curl https://krew.sh/preflight|bash
```suggestion
curl https://krew.sh/preflight | bash
```

2022-03-10 23:26 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-online.md
> +curl https://krew.sh/preflight|bash
```suggestion
curl https://krew.sh/preflight | bash
```

2022-03-10 23:26 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-airgapped.md
> +curl https://krew.sh/preflight|bash
```suggestion
curl https://krew.sh/preflight | bash
```

2022-03-10 23:26 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-automation.md
> +When one or more strict preflight checks are present, the application deployment is blocked until these strict checks are ran. Strict preflight checks must not contain failures and will block the rel
```suggestion
When one or more strict preflight checks are present, the application deployment is blocked until these strict checks run. Strict preflight checks must not contain failures and will block the release from being deployed until the failures are resolved. A vendor may specify strict preflight checks to help enforce that specific requirements are  met before the application can be deployed. 
```

2022-03-10 23:26 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-automation.md
> +When installing with [minimal role-based access control (RBAC)](../reference/custom-resource-application#requireminimalrbacprivileges), the app manager recognizes if the preflight checks have failed
```suggestion
When installing with [minimal role-based access control (RBAC)](../reference/custom-resource-application#requireminimalrbacprivileges), the app manager recognizes if the preflight checks have failed due to insufficient privilege. When this occurs, a `kubectl preflight` command is displayed that can be run manually in the cluster to run the preflight checks. When the command runs and completes, the results are automatically uploaded to the app manager.
```

2022-03-10 23:26 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-online.md
> +When one or more strict preflight checks are present, the application deployment is blocked until these strict checks are ran. Strict preflight checks must not contain failures and will block the rel
```suggestion
When one or more strict preflight checks are present, the application deployment is blocked until these strict checks run. Strict preflight checks must not contain failures and will block the release from being deployed until the failures are resolved. A vendor may specify strict preflight checks to help enforce that specific requirements are  met before the application can be deployed. 
```

2022-03-10 23:26 UTC, ajp-io commented on docs/enterprise/installing-existing-cluster-online.md
> +When installing with [minimal role-based access control (RBAC)](../reference/custom-resource-application#requireminimalrbacprivileges), the app manager recognizes if the preflight checks have failed
```suggestion
When installing with [minimal role-based access control (RBAC)](../reference/custom-resource-application#requireminimalrbacprivileges), the app manager recognizes if the preflight checks have failed due to insufficient privilege. When this occurs, a `kubectl preflight` command is displayed that can be run manually in the cluster to run the preflight checks. When the command runs and completes, the results are automatically uploaded to the app manager.
```

2022-03-10 23:26 UTC, ajp-io commented on docs/reference/custom-resource-application.md
> +During minimal role-based access control (RBAC) installations where a `strict` [preflight](../vendor/preflight-support-bundle-creating#creating-preflight-checks) is specified, you can use the kots CL
The way this is described in other sections with the `kubectl preflight` command makes sense to me.

2022-03-10 23:26 UTC, ajp-io commented on docs/reference/kots-cli-set-config.md
> +When the `--deploy` option is provided and there are [`strict preflights`](../docs/vendor/preflight-support-bundle-creating.md), the preflight checks will always run. The deployment will wait up to 1
Does this mean it automatically deploys after 15 minutes regardless of whether the preflights have completed? Not sure what happens after 15 minutes.

2022-03-10 23:26 UTC, ajp-io commented on docs/reference/kots-cli-upload.md
> +When the `--deploy` option is provided and there are [`strict preflights`](../docs/vendor/preflight-support-bundle-creating.md), the preflight checks will always run. The deployment will wait up to 1
Same as above. Does this mean it automatically deploys after 15 minutes regardless of whether the preflights have completed? Not sure what happens after 15 minutes.

2022-03-10 23:26 UTC, ajp-io commented on docs/reference/kots-cli-upstream-upgrade.md
> +When the `--deploy` option is provided and there are [`strict preflights`](../docs/vendor/preflight-support-bundle-creating.md), the preflight checks will always run. The deployment will wait up to 1
Same as above. Does this mean it automatically deploys after 15 minutes regardless of whether the preflights have completed? Not sure what happens after 15 minutes.

2022-03-11 00:42 UTC, JustinN-Replicated commented on docs/reference/kots-cli-set-config.md
> +When the `--deploy` option is provided and there are [`strict preflights`](../docs/vendor/preflight-support-bundle-creating.md), the preflight checks will always run. The deployment will wait up to 1
I made some adjustments to address this

2022-03-11 00:53 UTC, JustinN-Replicated commented
@ajp-io I think I addressed all of your comments - thanks for the review! 
@jonquil2002 something we should consider is where we should do a call out for when this feature was introduced - so something like:
> Introduced in the Replicated app manager v1.67.0
Will need to make sure we have the correct version of course.

2022-03-11 14:23 UTC, jonquil2002 commented on docs/enterprise/updating-apps.md
> +Warnings do not preclude the upgrade to a new version. The installer may elect to ignore warnings and proceed with the upgrade.
@JustinN-Replicated Is "the installer" the user (a person) or the Kubernetes installer or something else? If it's not a person, we might want to say "the installation".

2022-03-11 15:13 UTC, JustinN-Replicated commented on docs/enterprise/updating-apps.md
> +Warnings do not preclude the upgrade to a new version. The installer may elect to ignore warnings and proceed with the upgrade.
Honestly, I can't recall (I'm not sure if I had originally wrote this) but I lean towards the person (ie the person who is installing)

2022-03-11 18:35 UTC, jonquil2002 submitted a review, later dismissed
lgtm

2022-03-11 18:43 UTC, JustinN-Replicated approved these changes
lgtm

2022-03-11 19:41 UTC, JustinN-Replicated submitted a review, later dismissed
lgtm

2022-03-11 19:59 UTC, JustinN-Replicated approved these changes

2022-03-11 20:11 UTC, ajp-io approved these changes
Couple small tweaks but all good now.

2022-03-11 20:15 UTC, jonquil2002 approved these changes
lgtm

2022-03-21 20:42 UTC, jonquil2002 approved these changes
lgtm

2022-03-21 20:45 UTC, merged