44677 new info about automatic deploys and udpates
replicatedhq/replicated-docs pull request #216
Opened 2022-03-10 22:43 UTC by paigecalvert

SC: https://app.shortcut.com/replicated/story/44677/automatic-updates-docs

Eng SC: https://app.shortcut.com/replicated/story/44111/automatic-upgrades-should-sequence-based-on-semvers-if-the-channel-is-semver-enabled-otherwise-they-should-sort-based-on

2022-03-10 23:36 UTC, ajp-io requested changes

2022-03-10 23:36 UTC, ajp-io commented on docs/enterprise/updating-apps.md
> +1. To update the application, click **Continue** on the preflight checks page. Or,
Is there a continue button there? The screenshot above shows a re-run button, which is what I recall.

2022-03-10 23:36 UTC, ajp-io commented on docs/enterprise/updating-apps.md
> +1. In the Configure automatic updates dialog, under Automatically check for updates,
Do we not bold or put in quotations marks the headings? Just curious.

2022-03-10 23:36 UTC, ajp-io commented on docs/enterprise/updating-apps.md
> +   to automatically deploy only new major versions, select **Automatically deploy new major versions**.
I think it would be good to list the options. Also, you can't only deploy majors, so I changed it to patches.
```suggestion
   * **For applications that use semantic versioning**: Select an option in the dropdown
   to specify the versions that the admin console automatically deploys. You can choose to
   automatically deploy patch versions; patch and minor versions; or patch, minor, and
   major versions. For example, to automatically deploy only new patch versions, select 
   **Automatically deploy new patch versions**.
```

2022-03-11 00:16 UTC, paigecalvert commented on docs/enterprise/updating-apps.md
> +1. To update the application, click **Continue** on the preflight checks page. Or,
Great catch; I did not edit any of the existing technical content in this section just for the scope of this story, but I just pulled up an app and it looks like there are a few things wrong here. There is no "Preflight results" button--there a little logo that says "View preflight checks" when you hover over it.

And you are absolutely correct that there is no "Continue" button, let alone one that would deploy the app. I wonder if this is a nod to the preflight checks that run when you first install an application.

I'll edit to remove "Preflight results" and also to remove the line about the Continue button all together

2022-03-11 00:20 UTC, paigecalvert commented on docs/enterprise/updating-apps.md
> +1. In the Configure automatic updates dialog, under Automatically check for updates,
This actually came up recently when Jonquil and I were adding to the style guide :) Here's what we decided: https://docs.google.com/document/d/1_TcMD7c2r89rrMxJ5FOmSLEZ7TZda-AIs_MczTsRcs0/edit?disco=AAAAVGwDXjk

2022-03-11 00:29 UTC, paigecalvert commented on docs/enterprise/updating-apps.md
> +   to automatically deploy only new major versions, select **Automatically deploy new major versions**.
Nice--thank you.

For those options: I recommend that we don't list the options in the tech doc for a couple reasons: 1) it becomes an artifact that is just begging to get out of date and 2) since the user will be reading the options in the UI as they go through the procedure, it won't provide additional value to have it listed in the doc too.

I was thinking that providing that one example would be sufficient for conveying the logic of the options. But definitely let me know what you think and if you are ok with this approach

(If you are ok with it, I can go in and make the major --> patch edit that you caught)

2022-03-11 02:26 UTC, ajp-io commented on docs/enterprise/updating-apps.md
> +   to automatically deploy only new major versions, select **Automatically deploy new major versions**.
Given that semantic versioning only has patch, minor, and major version components, it's not something that will change or get out of date IMO. That being said, the example is illustrative. I might choose to use patches and minor versions as the example, since that shows a combination rather than just a single type of version. That seems to convey it better to me. I edited my suggestion above if you want to review/commit it.

2022-03-11 02:29 UTC, ajp-io commented on docs/enterprise/updating-apps.md
> +1. To update the application, click **Continue** on the preflight checks page. Or,
Yeah, the continue button is definitely present during the initial install, so it could have gotten confused there. I'll keep an eye out for your updates.

2022-03-11 15:51 UTC, paigecalvert commented on docs/enterprise/updating-apps.md
> +1. To update the application, click **Continue** on the preflight checks page. Or,
Done! https://github.com/replicatedhq/replicated-docs/pull/216/commits/1c849d41833761ec2397defa0878851a2662607c

2022-03-11 20:32 UTC, ajp-io commented on docs/enterprise/updating-apps.md
> +Preflight failures and warnings do not prevent the upgrade to a new version. You can decide to ignore these failures and proceed with the upgrade.
The blue team is about to merge docs on strict preflights, so we should amend this statement to reflect that work too.

2022-03-11 20:32 UTC, ajp-io commented on docs/enterprise/updating-apps.md
> +Preflight failures and warnings do not prevent the upgrade to a new version. You can decide to ignore these failures and proceed with the upgrade.
The blue team is about to merge docs on strict preflights, so we should amend this statement to reflect that work too.

2022-03-11 20:45 UTC, jonquil2002 commented on docs/enterprise/updating-apps.md
> +Preflight failures and warnings do not prevent the upgrade to a new version. You can decide to ignore these failures and proceed with the upgrade.
The blue team has updated this topic to reflect that in their PR. My advice is to merge this, and then when the other PR is merged on Monday, they'll have to accept/pull your changes in. They're releasing theirs on Monday.

2022-03-11 20:45 UTC, jonquil2002 commented on docs/enterprise/updating-apps.md
> +Preflight failures and warnings do not prevent the upgrade to a new version. You can decide to ignore these failures and proceed with the upgrade.
The blue team has updated this topic to reflect that in their PR. My advice is to merge this, and then when the other PR is merged on Monday, they'll have to accept/pull your changes in. They're releasing theirs on Monday.

2022-03-11 20:46 UTC, jonquil2002 approved these changes
lgtm as is - without the strict preflight info bc it's included in the blue team's PR for Monday.

2022-03-11 20:58 UTC, ajp-io commented
This is not yet released, so we shouldn't merge these docs yet.

2022-03-11 20:58 UTC, ajp-io approved these changes

2022-03-21 20:41 UTC, merged