initial commit of required release content
replicatedhq/replicated-docs pull request #251
Opened 2022-03-23 17:51 UTC by paigecalvert

https://app.shortcut.com/replicated/story/45256/document-the-ability-to-make-an-app-version-required

2022-03-24 21:05 UTC, ajp-io requested changes

2022-03-24 21:05 UTC, ajp-io commented on docs/vendor/releases-promoting.md
> +      When you mark a version as required and `allowRollback` is set to `true` in the Application custom resource manifest, users can no longer re-deploy, or _roll back_ to, versions earlier than the
The required version needs to be deployed before the non-rollback scenario occurs. Does this still work?
```suggestion
      Even if `allowRollback` is set to `true` in the Application custom resource, users cannot redeploy, or _roll back_, to versions earlier than the required version once the required version is deployed. For more information about rollbacks, see [allowRollback](../reference/custom-resource-application#allowrollback) in the _Application_ custom resource topic.
```

2022-03-24 21:22 UTC, paigecalvert commented on docs/vendor/releases-promoting.md
> +    * **Version label**: Enter a version label. You can use the semantic version format if you are using the Replicated app manager v1.58.0 or later. If you are using semantic versioning, you must al
Nice, I think this is a big improvement. LMK if there is more here that you think it's worth opening a separate docs story for, but will go ahead and commit this suggestion to this PR.

2022-03-24 21:26 UTC, paigecalvert commented on docs/vendor/releases-promoting.md
> +      When you mark a version as required and `allowRollback` is set to `true` in the Application custom resource manifest, users can no longer re-deploy, or _roll back_ to, versions earlier than the
Nice, good clarification. I'm going to push a new commit to rewrite this suggestion a touch. 

q: saw that you removed the word manifest. We've been using "custom resource manifest file"/"custom resource manifest" when referring to the actual yaml manifest file for a custom resource. Is this incorrect? Want to make sure we update that guidance if so.

2022-03-24 21:35 UTC, ajp-io commented on docs/vendor/releases-promoting.md
> +      When you mark a version as required and `allowRollback` is set to `true` in the Application custom resource manifest, users can no longer re-deploy, or _roll back_ to, versions earlier than the
That was just an oversight. I put a comma in the wrong place here too. Whoops!

2022-03-25 17:01 UTC, paigecalvert commented on docs/vendor/releases-promoting.md
> +      When you mark a version as required and `allowRollback` is set to `true` in the Application custom resource manifest, users can no longer re-deploy, or _roll back_ to, versions earlier than the
![Screen Shot 2022-03-25 at 11 00 19 AM](https://user-images.githubusercontent.com/11523028/160167147-1ce43ad9-f03d-4f06-ae48-8a60d97441ed.png)

Here's the updated note-- Very similar to your suggestion, just flipped around the order so that the most important stuff comes first.

2022-03-25 19:12 UTC, ajp-io commented on docs/vendor/releases-promoting.md
> +      When you mark a version as required and `allowRollback` is set to `true` in the Application custom resource manifest, users can no longer re-deploy, or _roll back_ to, versions earlier than the
Perf

2022-03-25 22:12 UTC, jonquil2002 approved these changes
lgtm

2022-04-04 13:34 UTC, ajp-io commented on docs/vendor/releases-promoting.md
> +      After users deploy a required version, they can no longer redeploy, or _roll back_ to, versions earlier than the    required version, even if `allowRollback` is `true` in the Application custom
```suggestion
      After users deploy a required version, they can no longer redeploy, or _roll back_ to, versions earlier than the required version, even if `allowRollback` is `true` in the Application custom resource manifest. For more information about rollbacks, see [allowRollback](../reference/custom-resource-application#allowrollback) in the _Application_ custom resource topic.
```

2022-04-04 13:35 UTC, ajp-io approved these changes

2022-04-04 13:39 UTC, jonquil2002 approved these changes

2022-04-05 00:02 UTC, merged