Improve info on KOTS version options
replicatedhq/replicated-docs pull request #252
Opened 2022-03-23 20:24 UTC by jonquil2002

2022-03-29 17:09 UTC, paigecalvert approved these changes
Thank you @jonquil2002 🙌 

I added my comments and suggestions in a google doc, because it was just a little easier for me to organize my thoughts over there rather than right in the PR: https://docs.google.com/document/d/1GrgqmFcBqnNdNBeMTJah0_fwAsGH8kk40aWf4XAcz3g/edit#heading=h.h2y35tiskocu

LMK if you had any questions or want to look at anything together :)

2022-03-29 17:09 UTC, paigecalvert commented on docs/reference/custom-resource-application.md
> +
You were likely already been planning to add this in later after the new topic has been merged, but adding a reminder note about linking to the new conceptual topic from this references topic for more info

2022-03-30 17:58 UTC, jonquil2002 commented on docs/reference/custom-resource-application.md
> +
Yep, have done so. Had it in mind, but good to be reminded since I hadn't done it yet.

2022-03-30 17:59 UTC, jonquil2002 commented
@paige. Implemented your edits. Can you take another look and approve? Also just gave Alex only the business reason sections to make sure they're technically correct. Thanks!

2022-03-30 21:42 UTC, paigecalvert commented
Looks great!!

I just have a recommendation on this line, but I figure this could be something you're working with Alex on anyway, so feel free to take it or leave it :)

"This can be useful when you want to get users on the same version of KOTS that you have tested or for using new features that are supported on a minimum version of KOTS."

--> "when you want to get users on the same version of KOTS that you have tested": rather than "have tested", for min version, it's more about the version that vendors are currently testing against on an ongoing basis when they are releasing new versions of their app (the assumption would be that they have already tested all older versions)
--> "or for using new features" feels like maybe it's the vendor using the new features, when it is more that the vendor wants their user to be able to use the feature. 

Suggestion would be something like:
"This can be useful for ensuring your users upgrade to the version of KOTS that you are using for testing your application releases. Setting a minimum version can also be useful when you want your users to have access to a KOTS feature that was released in a later version than they currently have installed. "

(again, def makes sense to run the above by Alex anyway)

2022-03-30 21:43 UTC, paigecalvert approved these changes

2022-03-31 21:10 UTC, jonquil2002 commented
@ajp-io Can you review this since Amber will be out tomorrow? Paige already did the editorial review. Should be in good shape for approval, unless something is technically incorrect.

Re: the task-based content we discussed, we can create a separate story for that if it's needed. We're working more iteratively on enhancements now. Lmk if you have any questions though.

2022-04-01 14:00 UTC, ajp-io requested changes

2022-04-01 14:00 UTC, ajp-io commented on docs/reference/custom-resource-application.md
> +The app manager is based on the KOTS open source project. The KOTS version is the same as the app manager version. For example, KOTS v1.60 is the same as the app manager v1.60. For more information a
Personally, I'd recommend not adding this here as it only applies to Kubernetes installer-created clusters, so it's not a general source of information about KOTS.
```suggestion
The app manager is based on the KOTS open source project. The KOTS version is the same as the app manager version. For example, KOTS v1.60 is the same as the app manager v1.60.
```

2022-04-01 14:00 UTC, ajp-io commented on docs/reference/custom-resource-application.md
> +The app manager is based on the KOTS open source project. The KOTS version is the same as the app manager version. For example, KOTS v1.60 is the same as the app manager v1.60. For more information a
Could be a separate PR, but we have a similar note about KOTS/app manager [here](https://deploy-preview-252--replicated-docs.netlify.app/reference/template-functions-static-context#kotsversion), so we should make these notes identical/consistent.

2022-04-01 14:00 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +The Replicated app manager is based on the KOTS open source project. The KOTS version is the same as the app manager version. For example, KOTS v1.60 is the same as the app manager v1.60. For more in
I'll put my suggestion here again, but let me know if I'm missing a reason to keep this here.
```suggestion
The Replicated app manager is based on the KOTS open source project. The KOTS version is the same as the app manager version. For example, KOTS v1.60 is the same as the app manager v1.60.
```

2022-04-01 14:00 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +When you promote a new release specifying a minimum KOTS version that is later than what a user currently has deployed, that application version appears in the version history of the admin console af
I got confused for a second when reading this, so I feel it's clearer to mention the check for updates sooner.
```suggestion
When you promote a new release specifying a minimum KOTS version that is later than what a user currently has deployed, and that user checks for updates, that application version appears in the version history of the admin console. However, it is not downloaded.
```

2022-04-01 14:00 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +The admin console temporarily displays an error message that informs the user that they must update KOTS before downloading the application version. This error also displays when the user checks for
Now that we have better docs on updating KOTS/app manager, we could link to those here.

Also, would this now be too long as one paragraph? I split it up just in case, but that's up to you.
```suggestion
The admin console temporarily displays an error message that informs the user that they must update KOTS before downloading the application version. This error also displays when the user checks for updates with the [`kots upstream upgrade`](../reference/kots-cli-upstream-upgrade) command.

KOTS cannot update itself automatically, and users cannot update KOTS from the admin console. For more information on updating KOTS, see [Updating the Admin Console on an Existing Cluster](../enterprise/updating-existing-cluster) and [Updating the Admin Console on a Kubernetes Installer-Created Cluster](../enterprise/updating-embedded-cluster).
```

2022-04-01 14:00 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +After updating KOTS to the minimum version or later, users can use the admin console or use the [`kots upstream download`](../reference/kots-cli-upstream-download) command to download the release.
```suggestion
After updating KOTS to the minimum version or later, users can use the admin console or use the [`kots upstream download`](../reference/kots-cli-upstream-download) command to download the release and subsequently deploy it.
```

2022-04-01 14:00 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +If a user's admin console is running a version of KOTS that is earlier than the target version specified in the new version of the application, the admin console displays a banner indicating that a n
```suggestion
If a user's admin console is running a version of KOTS that is earlier than the target version specified in a new version of the application, the admin console displays a notification in the footer, indicating that a newer supported version of KOTS is available.
```

2022-04-01 14:00 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +For more information about the KOTS add-on, see [KOTS add-on](https://kurl.sh/docs/add-ons/kotsadm) in the open source kURL documentation.
This is a good place to mention this since we're specifically talking about kURL clusters.

2022-04-01 14:36 UTC, jonquil2002 commented on docs/vendor/packaging-kots-versions.md
> +Minimum and target KOTS versions are optional features that are configured in the Application custom resource file. The attributes in this file help to control the application experience but are not
It was copy/pasted from the first paragraph on this page, to give context as to how the Application custom resource file works as a whole. https://docs.replicated.com/vendor/packaging-custom-resources

2022-04-01 14:40 UTC, jonquil2002 commented on docs/vendor/packaging-kots-versions.md
> +For more information about the KOTS add-on, see [KOTS add-on](https://kurl.sh/docs/add-ons/kotsadm) in the open source kURL documentation.
Can you clarify where you think that needs to go? For example, it does say "For installations to a cluster created by the Replicated Kubernetes installer"...but I could make the two paragraphs into one, which might make that clearer. Would that help?

2022-04-01 15:00 UTC, jonquil2002 commented on docs/reference/custom-resource-application.md
> +The app manager is based on the KOTS open source project. The KOTS version is the same as the app manager version. For example, KOTS v1.60 is the same as the app manager v1.60. For more information a
Although we do want consistency, with using docs as code there is no way to use snippets for consistency. We tried adding variables and it was ugly. Making the other note consistent with this one will require a separate PR. Thanks for pointing that other one out.

2022-04-01 15:37 UTC, jonquil2002 commented on docs/vendor/packaging-kots-versions.md
> +Minimum and target KOTS versions are optional features that are configured in the Application custom resource file. The attributes in this file help to control the application experience but are not
I could clarify it be saying "The attributes in the Application custom resource help to control...." How does that sound to you?

2022-04-01 15:44 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +Minimum and target KOTS versions are optional features that are configured in the Application custom resource file. The attributes in this file help to control the application experience but are not
That link was helpful, thanks. The custom resources themselves aren't deployed to the cluster, whereas this makes it sound like the attributes aren't deployed to the cluster. I think this might be clearer.
```suggestion
Minimum and target KOTS versions are optional features that are configured in the Application custom resource file. The attributes in this custom resource help to control the application experience, but the custom resource is not deployed to the cluster. For more information, see [Application Custom Resource](../reference/custom-resource-application).
```

2022-04-01 15:45 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +For more information about the KOTS add-on, see [KOTS add-on](https://kurl.sh/docs/add-ons/kotsadm) in the open source kURL documentation.
I wasn't requesting any change, just affirming that this is a good example of mentioning the KOTS add-on, since this is in fact about kURL clusters.

2022-04-01 16:56 UTC, jonquil2002 commented on docs/vendor/packaging-kots-versions.md
> +For more information about the user experience for updates, see [How the Admin Console Handles minKotsVersion](#how-the-admin-console-handles-minkotsversion).
We do but I don't think they're supported in MD titles/headings bc it was migrated without backticks. Not sure if they're supported in hyperlinking either, but I can give it a try.

2022-04-01 18:10 UTC, jonquil2002 commented on docs/vendor/packaging-kots-versions.md
> +For more information about the KOTS add-on, see [KOTS add-on](https://kurl.sh/docs/add-ons/kotsadm) in the open source kURL documentation.
Thanks!

2022-04-01 18:18 UTC, jonquil2002 commented on docs/vendor/packaging-kots-versions.md
> +### How the Admin Console Handles targetKotsVersion
The CSS handles this in an ugly way, so we're not adding the backticks in titles/headings right now. Added it to a story in Shortcut since there are other CSS changes that we'd like to have.

2022-04-01 18:26 UTC, jonquil2002 commented
@ajp-io All comments are resolved. Thanks for the technical clarity & suggestions. Please approve if possible. Thanks.

2022-04-01 19:39 UTC, ajp-io approved these changes
Approved but did have a few final thoughts.

2022-04-01 19:39 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +The `minKotsVersion` attribute in the Application manifest file defines the minimum KOTS version that is required by the application release. This can be useful when you want to get users who are lag
This feels like more direct language. Let me know if you agree.
```suggestion
The `minKotsVersion` attribute in the Application manifest file defines the minimum KOTS version that is required by the application release. This is useful when you want to get users who are lagging behind to update to a more recent KOTS version, or if your application requires functionality that was introduced in a particular KOTS version.
```

2022-04-01 19:39 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +For more information about the user experience for updates, see [How the Admin Console Handles `minKotsVersion`](#how-the-admin-console-handles-minkotsversion).
```suggestion
For more information about the user experience when a minimum KOTS version is specified, see [How the Admin Console Handles `minKotsVersion`](#how-the-admin-console-handles-minkotsversion).
```

2022-04-01 19:39 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +After updating KOTS to the minimum version or later, users can use the admin console or use the [`kots upstream download`](../reference/kots-cli-upstream-download) command to download the release and
```suggestion
After updating KOTS to the minimum version or later, users can use the admin console or the [`kots upstream download`](../reference/kots-cli-upstream-download) command to download the release and subsequently deploy it.
```

2022-04-01 19:39 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> + Including `targetKotsVersion` in the Application manifest file enforces compatibility checks for new installations. It blocks the installation if a user tries to install a version that is later than
```suggestion
 Including `targetKotsVersion` in the Application manifest file enforces compatibility checks for new installations. It blocks the installation if a user tries to install a version of KOTS that is later than the target version. For example, this can prevent users from installing a version of KOTS that you have not tested yet.
```

2022-04-01 19:39 UTC, ajp-io commented on docs/vendor/packaging-kots-versions.md
> +For more information about the user experience for updates, see [How the Admin Console Handles `minKotsVersion`](#how-the-admin-console-handles-minkotsversion).
Also just curious if this is necessary since this section is right beneath it and we don't have a similar note for target KOTS version

2022-04-01 21:02 UTC, merged