45428: Add `supportsMinimalRBACPrivilege` feature
replicatedhq/replicated-docs pull request #262
Opened 2022-03-24 18:29 UTC by jonquil2002

SC: https://app.shortcut.com/replicated/story/45428/add-the-supportsminimalrbacprivileges-feature

2022-03-25 14:28 UTC, ajp-io requested changes

2022-03-25 14:28 UTC, ajp-io commented on docs/vendor/packaging-rbac.md
> +* `supportMinimalRBACPrivileges` - Applicable to existing clusters only. When set to `true`, the app manager enables a namespace-scoped Role and RoleBinding on a per-customer basis. Therefore, this s
```suggestion
* `supportsMinimalRBACPrivileges` - Applicable to existing clusters only. When set to `true`, the app manager supports creating a Role and RoleBinding, granting the admin console access to all resources in the namespace, but not to any resources outside of the namespace. Minimal RBAC will not be used by default. It will only be used when the `--use-minimal-rbac` flag is passed to the `kots install` command. If you want a subset of customer installations to use minimal RBAC, use this option.
```

2022-03-25 14:28 UTC, ajp-io commented on docs/vendor/tutorial-installing-with-cli.md
> +    When this occurs, a `kubectl preflight` command is displayed that lets the end user manually run the preflight checks and upload the results automatically to the app manager. For more information
```suggestion
    When this occurs, a `kubectl preflight` command is displayed that lets the end user manually run the preflight checks and upload the results automatically to the app manager. For more information about configuring RBAC privileges, see [`requireMinimalRBACPrivileges`](../reference/custom-resource-application#requireminimalrbacprivileges) and [`supportsMinimalRBACPrivileges`](../reference/custom-resource-application#supportsminimalrbacprivileges) in the Application custom resource.
```

2022-03-25 14:28 UTC, ajp-io commented on docs/reference/custom-resource-application.md
> +When set to `true`, the app manager creates a namespace-scoped Role and RoleBinding, instead of the default cluster-scoped ClusterRole and ClusterRoleBinding. Setting this flag applies to all custome
```suggestion
Allows minimal role-based access control (RBAC) to be used for all customer installations. When set to `true`, the app manager creates a namespace-scoped Role and RoleBinding, instead of the default cluster-scoped ClusterRole and ClusterRoleBinding.
```

2022-03-25 14:28 UTC, ajp-io commented on docs/reference/custom-resource-application.md
> +When installing with minimal RBAC, the app manager recognizes if the preflight checks fail due to insufficient privileges. For more information about RBAC, see [Namespace-scoped Access](../vendor/pac
Preflights is only one consideration. So let's not mention stuff here, but just link to it instead.
```suggestion
For more information about RBAC, see [Namespace-scoped Access](../vendor/packaging-rbac/#namespace-scoped-access) in _Configuring Role-based Access Control_.
```

2022-03-25 14:28 UTC, ajp-io commented on docs/reference/custom-resource-application.md
> +When installing with minimal role-based access control (RBAC), the app manager recognizes if the preflight checks fail due to insufficient privileges. For more information about RBAC, see [Namespace-
Preflights is only one consideration. So let's not mention stuff here, but just link to it instead.
```suggestion
For more information about RBAC, see [Namespace-scoped Access](../vendor/packaging-rbac/#namespace-scoped-access) in _Configuring Role-based Access Control_.
```

2022-03-25 14:28 UTC, ajp-io commented on docs/vendor/packaging-rbac.md
> +As listed above, an application can require cluster scoped access across all namespaces on all/wildcard k8 objects or to have access limited to its given namespace.
```suggestion
As listed above, an application can require cluster-scoped access across all namespaces on all/wildcard Kubernetes objects, or it can have access limited to its given namespace.
```

2022-03-25 17:16 UTC, jonquil2002 commented on docs/vendor/packaging-rbac.md
> +```
This was copy/pasted (and removed) from the reference topic for Application customs resources that was done with the Blue Team recently re: strict preflights. I'm don't recall why support bundles was included in this language. 

@JustinN-Replicated - Can you help me to clarify the issues that Alex brought up? Please take a look at this topic in the preview for the full context. https://deploy-preview-262--replicated-docs.netlify.app/vendor/packaging-rbac#namespace-scoped-access

2022-03-25 20:47 UTC, ajp-io commented on docs/vendor/packaging-rbac.md
> +The RBAC permissions are set during the initial installation. The admin console is running using the assumed identity and cannot change its own authorization. Changing the RBAC scope from cluster to
```suggestion
The RBAC permissions are set during the initial installation. The admin console runs using the assumed identity and cannot change its own authorization. If you change the RBAC scope for your application from cluster to namespace or vice versa, this will only affect new installations. Existing installations will continue to run with their current authorization.
```

2022-03-25 20:58 UTC, jonquil2002 commented on docs/vendor/packaging-rbac.md
> +* `supportMinimalRBACPrivileges` - Applicable to existing clusters only. When set to `true`, the app manager enables a namespace-scoped Role and RoleBinding on a per-customer basis. Therefore, this s
Added most of your suggestions, with tweaks for active voice and verb tense.

2022-03-25 21:30 UTC, jonquil2002 commented on docs/vendor/packaging-rbac.md
> +```
@JustinN-Replicated nevermind. I'm going to put this section to the way we had it before in the Application custom resource topic.

2022-03-25 22:06 UTC, jonquil2002 commented on docs/vendor/packaging-rbac.md
> +The RBAC permissions are set during the initial installation. The admin console is running using the assumed identity and cannot change its own authorization. Changing the RBAC scope from cluster to
Implemented most of the changes. We avoid using Latin words like via and vice-versa because they do not translate well. See what you think about "conversely".

2022-03-25 22:15 UTC, jonquil2002 commented
@alex - Made lots of changes, incorporated most of your. Please take a look when you have a chance. Thanks!

2022-03-25 23:29 UTC, ajp-io requested changes
We're very close now!

2022-03-25 23:29 UTC, ajp-io commented on docs/reference/custom-resource-application.md
> +Allows minimal role-based access control (RBAC) to be used for all customer installations. When set to `true`, the app manager creates a namespace-scoped Role and RoleBinding, instead of the default
```suggestion
Requires minimal role-based access control (RBAC) be used for all customer installations. When set to `true`, the app manager creates a namespace-scoped Role and RoleBinding, instead of the default cluster-scoped ClusterRole and ClusterRoleBinding. For more information about RBAC, see [Namespace-scoped Access](../vendor/packaging-rbac/#namespace-scoped-access) in _Configuring Role-based Access Control_.
```

2022-03-25 23:29 UTC, ajp-io commented on docs/reference/custom-resource-application.md
> +Allows minimal role-based access control (RBAC) for be used for a subset of customer installations. When set to `true`, the app manager supports creating a namespace-scoped Role and RoleBinding, inst
```suggestion
Allows minimal role-based access control (RBAC) to be used for a subset of customer installations. When set to `true`, the app manager supports creating a namespace-scoped Role and RoleBinding, instead of the default cluster-scoped ClusterRole and ClusterRoleBinding. Minimal RBAC will not be used by default. It will only be used when the `--use-minimal-rbac` flag is passed to the `kots install` command. For more information about RBAC, see [Namespace-scoped Access](../vendor/packaging-rbac/#namespace-scoped-access) in _Configuring Role-based Access Control_.
```

2022-03-25 23:29 UTC, ajp-io commented on docs/vendor/packaging-rbac.md
> +* `supportMinimalRBACPrivileges` - Applicable to existing clusters only. When set to `true`, the app manager supports creating a namespace-scoped Role and RoleBinding, granting the admin console acce
We don't mention the namespace-scoped part for `requireMinimalRBACPrivileges` right above, so I'm just making the text here match. Roles and RoleBindings are always namespace-scoped, so I think it's fine to not mention it. We mention the namespace scoping elsewhere.
```suggestion
* `supportMinimalRBACPrivileges` - Applicable to existing clusters only. When set to `true`, the app manager supports creating a Role and RoleBinding, granting the admin console access to all resources in the namespace, but not to any resources outside of the namespace. Minimal RBAC is not used by default. It is used only when the `--use-minimal-rbac` flag is passed to the `kots install` command. Use this option if you want a subset of customer installations to use minimal RBAC.
```

2022-03-25 23:29 UTC, ajp-io commented on docs/vendor/packaging-rbac.md
> +The RBAC permissions are set during the initial installation. The admin console runs using the assumed identity and cannot change its own authorization. Changing the RBAC scope from cluster to namesp
I take it my use of "vice versa" didn't cut it, but I don't think this reads right with conversely either. Especially since it's followed by "affects", so I read this as "conversely affects". Does this work?
```suggestion
The RBAC permissions are set during the initial installation. The admin console runs using the assumed identity and cannot change its own authorization. Changing the RBAC scope from cluster to namespace or from namespace to cluster affects only new installations. Existing installations continue to run with their current authorization.
```

2022-03-28 13:20 UTC, jonquil2002 commented on docs/enterprise/installing-existing-cluster-requirements.md
> +   **Note**: If the `requireMinimalRBACPrivileges` property is set to `true` in the Application custom resource manifest, or if the `supportsMinimalRBACPrivileges` property is set to `true` in the Ap
Yes, thanks for catching that.

2022-03-28 14:20 UTC, jonquil2002 commented on docs/reference/custom-resource-application.md
> +```
Yep, I found where it should go. LMK what you think of the changes.

2022-03-28 14:26 UTC, jonquil2002 commented
@ajp-io Please see what you think now.

2022-03-28 19:22 UTC, ajp-io commented on docs/vendor/packaging-rbac.md
> +Without access to cluster-scoped resources, some preflight checks are not be able to read the resources. These tools continue to function, but return less data. For more information, see [Creating Pr
Check me on whether that link is correct, but we should use a relative link.
```suggestion
Without access to cluster-scoped resources, some preflight checks are not be able to read the resources. These tools continue to function, but return less data. For more information, see [Creating Preflight Checks and Support Bundles](/vendor/preflight-support-bundle-creating).
```

2022-03-28 19:31 UTC, jonquil2002 commented on docs/vendor/packaging-rbac.md
> +Without access to cluster-scoped resources, some preflight checks are not be able to read the resources. These tools continue to function, but return less data. For more information, see [Creating Pr
Fixed. It also needed "../" in front of vendor, not just "/".

2022-03-28 19:43 UTC, ajp-io commented
Hey, @jonquil2002. The intent of my original comment was that I don't think we need to mention strict preflights at all on the Application custom resource page. When you use minimal RBAC, there are several tradeoffs since you're limiting access to one namespace in the cluster. The note about strict preflights is only one of several things that will be affected. But the goal of the Application custom resource page is just to explain the purpose/function of each field in the Application custom resource. So IMO, getting into the weeds about side effects of using an option in that spec is out of scope for that page. We should link to docs on minimal RBAC (as we already do), and those docs should explain the considerations. But the Application custom resource page itself should just explain the fields and their purpose.

So if we do that, I suggest we remove the note about strict preflights. Instead, the text about the minimal RBAC options should link to docs that explain what to consider when using minimal RBAC. Right now, we link to https://deploy-preview-262--replicated-docs.netlify.app/vendor/packaging-rbac#namespace-scoped-access. IMO that is sufficient. That doc explains what namespace-scoped access does, and it includes sub-sections on strict preflights, velero namespace, etc.

And I'd argue that this part you added doesn't belong here: https://deploy-preview-262--replicated-docs.netlify.app/vendor/preflight-support-bundle-creating#using-preflight-checks-with-minimal-rbac. Since these are vendor docs and this is more of an enterprise FYI since the user will have to run this command—it isn't directly related to the vendor creating the preflights.

Let me know if that makes sense and whether you agree.

2022-03-28 21:56 UTC, jonquil2002 commented
Ok, I changed it @ajp-io

2022-03-28 22:29 UTC, ajp-io approved these changes

2022-04-05 00:01 UTC, merged