Update policies-support-lifecycle.md
replicatedhq/replicated-docs pull request #2747
Opened 2024-10-16 21:36 UTC by AmberAlston

Initial draft to add more info about Alpha and Beta phases plus an edit to GA def

2024-10-16 22:18 UTC, crdant commented
I'd like to more emphatically call out that "beta" does not imply "lower quality" if we are comfortable with that.

2024-10-16 22:24 UTC, AmberAlston commented
> I'd like to more emphatically call out that "beta" does not imply "lower quality" if we are comfortable with that.

I'm open to that. Do you have a suggested edit @crdant ?

2024-10-16 23:08 UTC, paigecalvert reviewed
added some suggestions @AmberAlston !

2024-10-16 23:08 UTC, paigecalvert commented on docs/vendor/policies-support-lifecycle.md
> +    <td>A product, or a feature within a product, that has been validated as both production ready and value additive by a percentage of Replicated customers. For high-level products, the GA phase is
```suggestion
    <td>A product or feature that has been validated as both production-ready and value-additive by a percentage of Replicated customers. Products in the GA phase are typically those that are available for purchase from Replicated.</td>
```
Not sure if my edit on that last sentence gets to the heart of what you wanted to say or not.

I could also see a brief definition of what we mean by "production-ready and value-additive" potentially being helpful. For example, something like: "production-ready refers to features and products that meet the security, reliability, and performance needs of users"

2024-10-16 23:23 UTC, AmberAlston commented on docs/vendor/policies-support-lifecycle.md
> +    <td>A product, or a feature within a product, that is exploratory/experimental. It is typically not publicly documented, and access is limited to customers providing early feedback. While most al
* Good to remove mention about docs. I think that is implied enough by limited access in this case
* My concern in removing the call call about about GA products can have alpha or beta features is that it feels like we have to explain this A LOT. A product like CMX or EC can be GA, but there will be features within that product that are alpha or beta. Not everything is automatically GA just because the parent product is. 
* No, there is not a predictable or standard timeline to communicate. It varies greatly. I more wanted to imply that it's not forever and that the feature's status will change one way or another.

2024-10-16 23:28 UTC, AmberAlston commented on docs/vendor/policies-support-lifecycle.md
> +    <td><p>A product, or a feature within a product, that has not yet met Replicated’s definition of GA. Products that are GA themself may have certain Beta features for a limited time as new capabil
Similar comment above on 'a ga product may have beta features' edit

My initial hesitation on that "typically production ready" edit is that this is more true of BETA work in the last 2-3 years but not very true of some of the long-standing KOTS beta features. Those will age out though. I think your vision will probably resonate better with the vendor reading it and is technically true by the use of the word "typically"

2024-10-16 23:33 UTC, AmberAlston commented
Thanks @paigecalvert! 

I accepted and committed the 3rd suggestion. I agree a follow up explaining production readiness in more detail could be a good follow up iteration. I don't really want to try to explain "value-additive" meaning part of our definition of done in this limited content space. I think it's explanatory enough for now. We can reassess based on any feedback/

I answered your questions on the first two suggestions. I think some combination between your suggestions and my original will be the sweet spot. See what you think based on my question follow ups.

2024-10-17 13:28 UTC, crdant commented on docs/vendor/policies-support-lifecycle.md
> +    <td><p>A product, or a feature within a product, that has not yet met Replicated’s definition of GA. Products that are GA themself may have certain Beta features for a limited time as new capabil
The "typically production ready" language addresses my quality comment. Maybe something at the end of beta (and alpha?) like:

> Software released in the Beta phase follows the same build and test processes as software released in the GA phase and is generally of production quality.

2024-10-17 13:51 UTC, crdant requested changes

2024-10-17 13:51 UTC, crdant commented on docs/vendor/policies-support-lifecycle.md
> +    <td>A product, or a feature within a product, that is exploratory/experimental. It is typically not publicly documented, and access is limited to customers providing early feedback. While most al
I kind of liked having the docs detail in there. Maybe something like:
> Typically, access to alpha features and their documentation is limited to customers providing early feedback.

2024-10-17 15:59 UTC, AmberAlston commented on docs/vendor/policies-support-lifecycle.md
> +    <td><p>A product, or a feature within a product, that has not yet met Replicated’s definition of GA. Products that are GA themself may have certain Beta features for a limited time as new capabil
Let me see how I can try to work that last suggestion in without it getting repetitive. I think it's generally accurate for Beta features/product but not Alpha, which can include purposely not yet production ready experimental feature code.

2024-10-17 16:26 UTC, paigecalvert commented on docs/vendor/policies-support-lifecycle.md
> +    <td>A product, or a feature within a product, that is exploratory/experimental. It is typically not publicly documented, and access is limited to customers providing early feedback. While most al
Oops, ignore that ^ I think I posted this comment just after you pinged us to say it's ready for re-review :)

2024-10-17 16:56 UTC, merged