Do Not Merge - Blocked on Release - 46047 changing a license content
replicatedhq/replicated-docs pull request #278
Opened 2022-04-06 14:47 UTC by paigecalvert

2022-04-06 19:31 UTC, ajp-io commented
This shows the modal and the button in the background. Just FYI. 
![image](https://user-images.githubusercontent.com/7272359/162054034-41e42c39-31bf-4522-9384-787dfab45a0c.png)

2022-04-06 19:32 UTC, ajp-io requested changes

2022-04-06 19:32 UTC, ajp-io commented on docs/enterprise/updating-licenses.md
> +1. In the dialog, upload the new, paid license file that you received from your vendor.
```suggestion
1. In the dialog, upload the new license file that you received from your vendor.
```

2022-04-06 20:44 UTC, paigecalvert commented
Thanks @ajp-io, great corrections. Q: is it important at all to differentiate between changing to a new license, and changing to a new _type_ of license? I know for non-community licenses, users would click the sync button to update. For air gap, I suppose you technically do upload a "new" license. Anyway, not sure if this is important to differentiate or not, wanted to throw it out there.

2022-04-07 14:25 UTC, ajp-io commented
@paigecalvert That is a good question. It's definitely an interesting distinction. In a sense, you're not uploading a new license in air gap. It's the same license as far as the vendor portal is concerned, but you upload a different license _file_, since perhaps the details of the license have changed.

I view "new/different license" as a different customer (i.e., license) created in the vendor portal. And in that sense, we are changing the license here since it's a new customer (no longer using the one community customer/license that all community users upload). Whereas changing the license type can be accomplished with the same license—you just have to sync it.

So I'm okay with just saying that you're changing the license, since from a vendor portal POV that means you have created a new customer—you haven't just changed settings for an existing customer.

2022-04-07 14:26 UTC, ajp-io approved these changes

2022-04-08 21:38 UTC, merged