Do Not Merge - Blocked on Release - 46047 changing community licenses
replicatedhq/replicated-docs pull request #279
Opened 2022-04-06 15:27 UTC by paigecalvert

SC: https://app.shortcut.com/replicated/story/46047/orange-team-support-changing-a-license

Preview: https://deploy-preview-279--replicated-docs.netlify.app/vendor/licenses-about-types#community-licenses

Related enterprise user content: https://github.com/replicatedhq/replicated-docs/pull/278

2022-04-06 18:15 UTC, ajp-io commented on docs/vendor/licenses-about-types.md
> +paid license. This allows you to upgrade your users to a paid license without
It would be good to mention somewhere the fact that changing licenses is important since all community users might be on a single license. Otherwise, you could just change that customer's license type from community to paid. The reason you need to be able to upload a new license is that vendors might have all their community users on a single license.

2022-04-06 18:58 UTC, paigecalvert commented on docs/vendor/licenses-about-types.md
> +Community licenses are unpaid licenses intended for use with an open source version
@ajp-io should we also remove the word "unpaid"?

2022-04-06 18:59 UTC, paigecalvert commented on docs/vendor/licenses-about-types.md
> +* **Community**: The Community type is designed for an open source, community version of your
Great clarification. I'll revert this change. (Perhaps open source could be referenced as an example of a use case for community licenses)

2022-04-06 19:14 UTC, paigecalvert commented on docs/vendor/licenses-about-types.md
> +* **Community**: The Community type is designed for an open source, community version of your
Addressed in https://github.com/replicatedhq/replicated-docs/pull/279/commits/c91f9d9ebc9891972adce4e27863102733f28db3

2022-04-06 19:15 UTC, paigecalvert commented on docs/vendor/licenses-about-types.md
> +paid license. This allows you to upgrade your users to a paid license without
Ah got it. Clarified in https://github.com/replicatedhq/replicated-docs/pull/279/commits/c91f9d9ebc9891972adce4e27863102733f28db3. If you'd rather it not be mentioned at all, we can also just delete the sentence about how it also prevents users from having to reinstall (I figure that was just a workaround some vendors/users were doing?)

2022-04-06 19:29 UTC, ajp-io commented on docs/vendor/licenses-about-types.md
> +* **Support for changing to a paid license**: After installing an application with
It doesn't have to be a paid license. Hypothetically someone could change from community to a free trial license as part of a POC before purchasing. So we should avoid saying that it's a paid license, because it can be any license type. You could even change to another community license in theory. In short: if you have a community license, you can change licenses, and the new license can be anything.

2022-04-07 14:32 UTC, ajp-io requested changes
I think we're good after this :)

2022-04-07 14:32 UTC, ajp-io commented on docs/vendor/licenses-about-types.md
> +a community license, enterprise users can change their community license to a different type of
```suggestion
a community license, enterprise users can change their community license to a different
```

2022-04-07 15:52 UTC, paigecalvert commented on docs/vendor/licenses-about-types.md
> +* **Support for changing to a different license type**: After installing an application with
No no, all good! These were changes I had made before I asked the question over on the other PR. Just hadn't gone back to fix it here yet. I'm right with you 👍

2022-04-07 17:08 UTC, ajp-io approved these changes

2022-04-08 21:38 UTC, merged