Wait for Release - 48530: Application drop-down filter
replicatedhq/replicated-docs pull request #362
Opened 2022-05-18 20:19 UTC by jonquil2002

SC: https://app.shortcut.com/replicated/story/48530/orange-team-application-drop-down-filter

2022-05-19 00:16 UTC, paigecalvert approved these changes
lgtm -- just added one suggestion

2022-05-19 15:00 UTC, ajp-io requested changes

2022-05-19 17:13 UTC, jonquil2002 commented
@paigecalvert  @ajp-io  Ready for another review pass. Good ideas, thanks!

2022-05-19 17:16 UTC, ajp-io approved these changes
@miaawong These docs should get merged when we ship the updated application dropdown and new create app button.

2022-06-06 15:19 UTC, ajp-io reviewed
Thanks for resurfacing this PR. We decided against a dedicated New Application button, so that part needs to change to mention how it's in the dropdown (as before). But if you think the rest of the changes here are worth making, then we can definitely get this approved and merged.

2022-06-06 15:19 UTC, ajp-io commented on docs/vendor/releases-creating-releases.md
> +    - If you are logging in with an existing account: Click **New Application** or select an existing application.
We decided against a dedicated New Application button, so we moved this back into the dropdown. So creating a new app is in the dropdown again.

2022-06-06 18:23 UTC, jonquil2002 commented
Closing this PR because the feature was archived and the other non-feature changes are not needed due to another PR from last week.

2022-06-06 18:23 UTC, closed without merging

2022-06-06 21:38 UTC, ajp-io commented
@jonquil2002 One thing I liked in this PR was that instead of referencing a random link in the first step [here](https://docs.replicated.com/vendor/releases-creating-releases), we talk about how to find the New Application button. We. can make this change separately, but I would rather tell people to use the standard button instead of this random link. This link isn't accessible anywhere in the product—like you can't click something in the product to get to that. So I'd rather show people how they can do this in their normal workflow, rather than using a random link they have to bookmark.