DO NOT MERGE - 48601: Packaging Workflow
replicatedhq/replicated-docs pull request #363
Opened 2022-05-19 19:02 UTC by jonquil2002

SC: https://app.shortcut.com/replicated/story/48601/packaging-priorities-workflow

2022-06-01 15:17 UTC, jonquil2002 commented on docs/vendor/distributing-workflow.md
> +        <td>If your application is already packaged using Helm charts, see <a href="helm-installing-replicated-helm">Installing with the App Manager.</a></td>
Some changes were made in a different PR, which automatically resolves the title issue/ I've changed it here to reflect the new title, which specifically says Helm.

2022-06-01 19:35 UTC, jonquil2002 commented on docs/vendor/packaging-workflow.md
> +1. Blah, blah, blah
Ah. don't worry, this was a draft that we're not going to use. I presented two models to Paige and we decided to leave this one behind. I just hadn't deleted it yet, doing so now.

2022-06-01 19:37 UTC, jonquil2002 commented on docs/vendor/releases-creating-releases.md
> +[How to Package an Application for Production](packaging-workflow)
I deleted the latter.

2022-06-02 13:37 UTC, ajp-io commented on docs/vendor/distributing-workflow.md
> +1. Promote the release and test it by installing the release in a development environment with the license file that you created. You can use the environment that you created during one of the recomm
Is promoting considered part of packaging/distributing the release? Do we need to link to the docs on promoting a release? A similar question would be, in step 1, do we need to link to the section on creating a release? Or is it assumed those things are already known?

2022-06-03 13:09 UTC, ajp-io commented
I don't know if it belongs in this PR or another, but I found that the first link on this page (about using the private registry) doesn't have the correct anchor anymore. Maybe the section name changed at some point. https://deploy-preview-363--replicated-docs.netlify.app/vendor/packaging-private-registry-security

2022-06-03 13:21 UTC, ajp-io requested changes
A comment and one link that doesn't work

2022-06-03 13:21 UTC, ajp-io commented on docs/vendor/distributing-workflow.md
> +1. Push your images to the Replicated private registry if you plan to host your images that registry. See [Connecting to an Image Registry](packaging-private-images). Otherwise, proceed to the next s
Should this link point to this specific subsection instead? https://deploy-preview-363--replicated-docs.netlify.app/vendor/packaging-private-images#push-images-to-the-replicated-private-registry

2022-06-03 13:21 UTC, ajp-io commented on docs/vendor/distributing-workflow.md
> +        <td>If your application is already packaged using Helm charts, see <a href="helm-release">Adding Helm Charts to a Release</a>.</td>
Link doesn't work

2022-06-03 14:20 UTC, jonquil2002 commented
@ajp-io The broken link to Helm is bc the topic file name was changed in another PR and my branch isn't pulling that in from `main` for some reason. The link will work when this PR is merged. If not, I can open another PR to fix it. If you can approve this, I will merge and test that right away.

2022-06-03 16:53 UTC, ajp-io approved these changes

2022-06-03 18:17 UTC, merged