Wait for Release - 49002: Add Kubernetes Installer to a Release
replicatedhq/replicated-docs pull request #376
Opened 2022-05-27 15:32 UTC by jonquil2002

SC: https://app.shortcut.com/replicated/story/49002/orange-team-kubernetes-installer-improvements-iteration-1

Preview: https://deploy-preview-376--replicated-docs.netlify.app/vendor/packaging-embedded-kubernetes

2022-06-02 18:31 UTC, jonquil2002 commented
@ajp-io 

Regarding installing the non-latest version:

- It looks like this can only be done with the CLI right? Using `kubectl kots install [upstream uri] --app-version-label`?

- Does this apply to both methods of the Kubernetes installer?

- This is done by the enpterprise user? Does the vendor need to do anything?

Thanks.

2022-06-03 18:38 UTC, ajp-io commented on docs/vendor/packaging-embedded-kubernetes.md
>  1. On the **Kubernetes Installer** page, click **Create kubernetes installer**.
We updated that a little while ago actually.
<img width="375" alt="Screen Shot 2022-06-03 at 2 38 29 PM" src="https://user-images.githubusercontent.com/7272359/171926119-5d374f96-34b9-4a85-9c07-6623e3c2c913.png">

2022-06-03 19:05 UTC, ajp-io requested changes
Two small things. Would love to merge this today so that we can have some alpha docs out there to show a couple customers.

2022-06-03 19:05 UTC, ajp-io commented on docs/vendor/packaging-embedded-kubernetes.md
> +    <td><a href="packaging-embedded-kubernetes#create-a-kubernetes-installer-in-the-release-application">Included with the release (Beta)</a></td>
```suggestion
    <td><a href="packaging-embedded-kubernetes#create-a-kubernetes-installer-in-the-release-application">Included with the release (Alpha)</a></td>
```

2022-06-03 19:05 UTC, ajp-io commented on docs/vendor/packaging-embedded-kubernetes.md
> +1. Save and promote the release to your development environment to test your changes.
Since the installer isn't related to the release in this case, I think we should say "a release" since there isn't a particular release in view in this workflow.
```suggestion

1. Save and promote a release to your development environment to test your changes.
```

2022-06-03 19:45 UTC, jonquil2002 commented
@ajp-io  I committed your changes. Please approve and merge when ready :)

2022-06-03 19:56 UTC, ajp-io approved these changes

2022-06-03 19:56 UTC, merged