49805: Using Previous Versions of Releases
replicatedhq/replicated-docs pull request #393
Opened 2022-06-08 19:50 UTC by jonquil2002

SC: https://app.shortcut.com/replicated/story/49805/orange-team-k8s-installer-add-version-history-to-vendor-portal

Previews: 

- https://deploy-preview-393--replicated-docs.netlify.app/vendor/packaging-embedded-kubernetes

- https://deploy-preview-393--replicated-docs.netlify.app/vendor/releases-sharing-license-install-script

2022-06-09 17:35 UTC, paigecalvert reviewed
@jonquil2002 mainly just a higher level comment/question to start to make sure I am understanding correctly (I did not do much of the sentence level stuff)

2022-06-09 17:35 UTC, paigecalvert commented on docs/vendor/packaging-embedded-kubernetes.md
>  ## About installing an application without an existing cluster
(Heading should be all caps)

2022-06-09 17:35 UTC, paigecalvert commented on docs/vendor/packaging-embedded-kubernetes.md
>  1. From the Replicated [vendor portal](https://vendor.replicated.com), select **Releases > Create Release**.
This is probably not part of the story, so feel free to ignore. I've been recycling the following for the "open up a release" step:

>1. In the [vendor portal](https://vendor.replicated.com/apps), click **Releases**. Then, either click **Create release** to create a new release, or click **Edit YAML** to edit an existing release.

I bet we could cut down on the words, though it does articulate how you can either create a new release or edit an existing. In this case, adding a k8s installer spec is probably one of the later steps when you're editing a release

Side note: This step would be a great one to turn into a snippet

2022-06-09 17:35 UTC, paigecalvert commented on docs/vendor/packaging-embedded-kubernetes.md
> +## About Using Previous Release Versions
It feels like there might be one extra layer of context missing... It could just be the verb "using", but I am not sure what is meant by "using previous release versions".

The follow up question I have is: Using previous release versions for what? (What is the user trying to accomplish?)

I think you mention disaster recovery, so my guess would be that these instructions are for if a vendor needs to send an install command for a previous version of an app + installer to a customer. In this case, maybe "using" is "installing"?

I could see this content going in its own topic if that is the case, since the goal of installing a previous version of an app + installer is distinct and would happen at a different time than creating the K8s installer manifest.

LMK if these questions don't make any sense or if you want to pair on it (I'm not sure that I'm expressing it well)

2022-06-10 18:37 UTC, jonquil2002 commented
@paigecalvert @ajp-io  Ready for review. I made some heavy changes. Thanks so much for the help.

2022-06-13 23:27 UTC, paigecalvert submitted a review, later dismissed
This is looking great!! Added some suggestions, and a few questions. LMK if you want to look at it together at all

2022-06-13 23:27 UTC, paigecalvert commented on docs/vendor/releases-sharing-license-install-script.md
> +# Sharing License Files and Application Releases
Notes that apply in a few places:

- I noticed some typos where "an" should be "a". For example, "an previous". Could be good to run a search
- Release version terminology: "current" can sometimes be a little unclear (currently released? currently promoted on the given channel? currently installed from the ent users perspective?). Recommend scanning for places where "current" could be further explained and/or replaced with "latest" when referring to the latest version of an app
- Similar comment with "previous". "Earlier" might be more clear if you think it makes sense in this context

2022-06-13 23:27 UTC, paigecalvert commented on docs/vendor/releases-sharing-license-install-script.md
> +### Include an Kubernetes Installer (Beta)
"Include" almost suggests to me that, after doing this procedure, they will have included a k8s installer in their release. 

Based on the procedure, it sounds like they are sharing the installation command for a release where the k8s installer is included.

I also like how the first h3 calls out "existing cluster". To continue that pattern, I think it could be helpful for these to specifically call out that they are embedded cluster installation commands as well.

I know these headings can get really long as we're getting that specific, so what do you think about something like this with one more layer?

### Share an Existing Cluster Installation Command
### Share an Embedded Cluster Installation Command 

#### Kubernetes Installer Included in the Release
#### Kubernetes Installer Separate from the Release

The idea would be: you're either sharing existing or embedded. Then, within embedded, you're either sharing with the k8s installer included or separate.

2022-06-13 23:27 UTC, paigecalvert commented on docs/vendor/releases-sharing-license-install-script.md
> +If you created a Kubernetes installer specification that is separate from your application release, you can use an previous version of the application but the installation command uses the currently
Q: "If you created a Kubernetes installer specification that is separate from your application release" --> does this mean if they have ever created a k8s installer that is separate from any release, then this would need to be the consideration? Or, is it when they are trying to share a specific version for which the k8s installer is separate?

If it's the later, recommended re-write to highlight this: "When you share an installation command for a previous application version where the Kubernetes installer specification is separate from the release, the installation command always uses the currently-promoted version of the Kubernetes installer."

2022-06-14 01:08 UTC, ajp-io requested changes
Think I'm going to have to take another pass after you review these comments. But definitely take a look at where I mentioned that the method of copying the installer from the release history will be available for all of the installation methods mentioned here. That might change how you want to structure this, at least somewhat.

2022-06-14 01:08 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +1. Click **Release history** in the Latest Release pane for the channel you want to use.
Should "release" be lowercase here since it is on the webpage? I don't know since it's not bold, I wasn't sure if you were quoting it or not.
```suggestion
1. Click **Release history** in the Latest release pane for the channel you want to use.
```

2022-06-14 01:08 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +1. Copy the installation command for the version that you want to use and share it with your customer.
This method of copying the command from the release history page is going to work for all three of these methods. Does that change how you want to write/arrange this page? At minimum we should reference it in each section, but do we go into fewer details and just tell them to go copy the command? Or do we just mention that but still show them what the command will look like?

2022-06-14 01:08 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +      curl -sSL https://k8s.kurl.sh/APP-SLUG-beta-2.3.30 | sudo bash
Should this be more general or more specific? It's interesting that we generalize APP-SLUG but then choose a channel and version label arbitrarily. Seems like we should either be specific or general everywhere IMO.

2022-06-14 01:08 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +To use a previous application release version with a separate Kubernetes installer, run:
```suggestion
To use a previous application release version with the Kubernetes installer that is promoted to the channel, run:
```

2022-06-14 01:08 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +### Use a Separate Kubernetes Installer
```suggestion
### Use the Kubernetes Installer Promoted to the Channel
```

2022-06-14 01:29 UTC, paigecalvert commented on docs/vendor/releases-sharing-license-install-script.md
> +curl -sSL https://k8s.kurl.sh/APP-SLUG-CHANNEL | sudo bash -s app-version-label=VERSION
Ah, good catch. I think we said we want to use underscores for the placeholder text

2022-06-14 14:16 UTC, jonquil2002 commented on docs/vendor/releases-sharing-license-install-script.md
> +You can share previous versions of application releases for existing clusters or Kubernetes installer-created clusters for troubleshooting purposes.
Good idea.

2022-06-14 14:46 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +If you created a Kubernetes installer as part of your release, the version of the Kubernetes installer is included with the version of the application. This coupling makes it easy to provide users wi
I agree, though the suggested wording is a bit off since including the installer in the release is just one of the methods. Something like this could work: "For more information about methods for using a Kubernetes installer…"

2022-06-14 18:39 UTC, jonquil2002 commented on docs/vendor/releases-sharing-license-install-script.md
> +1. Click **Release history** in the Latest Release pane for the channel you want to use.
Yes, we really should use what's in the UI, as much as I dislike that general tech writing rule. Thanks for catching that.

2022-06-14 19:03 UTC, jonquil2002 commented on docs/vendor/releases-sharing-license-install-script.md
> +      curl -sSL https://k8s.kurl.sh/APP-SLUG-beta-2.3.30 | sudo bash
In this case, it is an example rather than the actual syntax, so it should be more specific. Good catch!

2022-06-14 21:32 UTC, jonquil2002 commented on docs/vendor/releases-sharing-license-install-script.md
> +# Sharing License Files and Application Releases
Thanks for the compliment and the chat. Just adding here for the record that we decided not to remove the note today, but will do so in as the versioning stories unfold.

2022-06-15 16:16 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +If you created a Kubernetes installer specification that is separate from your application release, you can use an previous version of the application but the installation command uses the currently
That's a good question. The distinction is really whether the release in question has an installer in it or not. The question needs to be asked on a per-release basis. So installing a previous version that includes an installer will work one way, and installing a previous version that doesn't include an installer will work the other way.

I think your wording is spot on.

2022-06-15 19:15 UTC, jonquil2002 commented on docs/vendor/releases-sharing-license-install-script.md
> +If you created a Kubernetes installer specification that is separate from your application release, you can use an previous version of the application but the installation command uses the currently
Yes, I thought her wording was great too.  :)

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/packaging-embedded-kubernetes.md
> +    <td>The installer manifest file is added to the application release. <br></br><br></br> Couples the installer and the application in the release, making them easier to test and use together. <br>
You got rid of the word "Specification" from the title of this section. Here we say "manifest file." Below we say "installer specification." These should be more consistent. Can we just say "Create an installer" in general, or do we have to say something like specification or manifest?

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/packaging-embedded-kubernetes.md
> +## Create a Kubernetes Installer in the Application Release (Beta)
```suggestion
## Create a Kubernetes Installer in the Application Release (Alpha)
```

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/packaging-embedded-kubernetes.md
> +    <td>The installer specification is created separately from the application release. <br></br><br></br> This option uses the Kubernetes installer that is currently promoted to the channel. Using a
```suggestion
    <td>The installer specification is created separately from the application release. <br></br><br></br> This option uses the Kubernetes installer that is currently promoted to the channel. Using the Kubernetes installer that is currently promoted to the channel can pose problems when installing previous versions of the application, since previous versions may not be tested with the currently promoted installer.</td>
```

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +You can share specific versions of application releases for existing clusters or Kubernetes installer provisioned clusters. This is useful when a customer needs to install a particular version or whe
I think we use this language elsewhere.
```suggestion
You can share specific versions of application releases for existing clusters or Kubernetes installer-created clusters. This is useful when a customer needs to install a particular version or when you need to install and troubleshoot a specific version.
```

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +### Use an Existing Cluster Installation Command
Something like this feels better to me, since the emphasis isn't on which command you use but on which environment you're installing to.
```suggestion
### Install to an Existing Cluster
```

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +### Use an Existing Cluster Installation Command
I don't know if we have other wording elsewhere, but this was my stab at it.

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +To use a specific application version for an existing cluster, run:
```suggestion
To install a specific application version to an existing cluster, run:
```

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +- `VERSION` with the version number.
If we want to do this as a first pass, that's fine, but I think we talked about how all installation commands will now be available on the release history page. So the steps below for going to that page to get the install commands could be used here too instead of hardcoding this.

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +If you created a Kubernetes installer manifest file as part of your release, this coupling makes it easy to provide users with a specific version of both the installer and the application. For more i
```suggestion
If you created a Kubernetes installer manifest file as part of your release, this coupling makes it easy to provide users with an installation command that uses the correct version of both the installer and the application. For more information about methods for creating Kubernetes installers, see [Creating a Kubernetes Installer](packaging-embedded-kubernetes).
```

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +To use a specific application version that includes the installer manifest:
```suggestion
To install a specific application version that includes the installer manifest:
```

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +1. Copy the installation command for the version that you want to use and share it with your customer.
This is still true, and I mention this in a comment above too.

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +1. Copy the installation command for the version that you want to use and share it with your customer.
Also, here is a screenshot that shows the "Install commands" button that you click to get to the install commands. Additionally, you have to choose the existing or embedded cluster tab to get the right command.
<img width="979" alt="Screen Shot 2022-07-01 at 3 49 03 PM" src="https://user-images.githubusercontent.com/7272359/176960367-1501bbab-3e17-48d9-b6f4-5d1ca0c48b4b.png">

2022-07-01 19:52 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +When you share an installation command for a previous application version where the Kubernetes installer specification is separate from the release, the installation command always uses the currently
```suggestion
When you share an installation command for a previous application version that doesn't include a Kubernetes installer specification, the installation command always uses the currently promoted Kubernetes installer. In this case, you might not have tested the latest Kubernetes installer specification with the earlier application version. For more information about Kubernetes installer methods, see [Creating a Kubernetes Installer](packaging-embedded-kubernetes).
```

2022-07-05 17:57 UTC, jonquil2002 commented on docs/vendor/packaging-embedded-kubernetes.md
> +    <td>The installer manifest file is added to the application release. <br></br><br></br> Couples the installer and the application in the release, making them easier to test and use together. <br>
Great question. As a results, we just worked on clarifying our usage of specification versus manifest, so I made those changes. Also, I think we can use "installer" when we're talking about it as a feature, but "installer manifest" when we're talking about configuring something in the manifest file or adding a manifest file to a release, etc. Hope that helps.

2022-07-05 18:05 UTC, jonquil2002 commented on docs/vendor/releases-sharing-license-install-script.md
> +You can share specific versions of application releases for existing clusters or Kubernetes installer provisioned clusters. This is useful when a customer needs to install a particular version or whe
We're trying out "provisioned" as we're really not keen on "-created". Though we may land on "Kubernetes installer cluster" TBD.

2022-07-07 01:33 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +## Share Currently Promoted Releases
Same comment here as above. Technically they're all currently promoted. This is more about "Share Most Recently Promoted Release" or "Share Latest Releases." I don't know that I'm happy with those wordings, but something like that.

2022-07-07 01:33 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +Installation commands are unique to each channel. Within each channel, there are installation commands for existing clusters and for Kubernetes installer provisioned clusters (embedded clusters).
```suggestion
Installation commands are unique to each channel. Within each channel, there are installation commands for existing clusters and for Kubernetes installer-created clusters (embedded clusters).
```

2022-07-07 01:33 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +To locate and share an installation command for a currently promoted release:
```suggestion
To locate and share an installation command for the most recently promoted release:
```

2022-07-07 01:33 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +You can share specific versions of application releases for existing clusters or Kubernetes installer provisioned clusters. This is useful when a customer needs to install a particular version or whe
```suggestion
You can share specific versions of application releases for existing clusters or Kubernetes installer-created clusters. This is useful when a customer needs to install a particular version or when you need to install and troubleshoot a specific version.
```

2022-07-07 01:33 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +  ![Existing Cluster Command](/images/embedded-cluster-command.png)
This image is great except that the command isn't correct. This version must not have an installer in it. The command should look something like this if the installer is in the release:
```
curl -sSL https://k8s.kurl.sh/alex-guestbook-2.3.50 | sudo bash
```
This image would be correct if we were using a separate Kubernetes installer.

2022-07-07 01:33 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +- `VERSION` with the version number.
You can still use the "Install Commands" modal for this method too. That modal displays the correct embedded installation command depending on whether the installer is in the release or not. So all three of these methods can/should use the install commands modal.

And in that case, the steps for all the cases are basically the same—the command just looks different for each. So it's up to you whether we need these all separated out or if it can be more condensed (like it is above for "Share Currently Promoted Releases."

2022-07-07 13:07 UTC, jonquil2002 commented on docs/vendor/releases-sharing-license-install-script.md
> +You can share specific versions of application releases for existing clusters or Kubernetes installer provisioned clusters. This is useful when a customer needs to install a particular version or whe
We're probably moving towards "provisioned". Keeping this as is for now.

2022-07-07 13:21 UTC, jonquil2002 commented on docs/vendor/releases-sharing-license-install-script.md
> +This topic describes how to share license files and installation commands for currently and previously promoted versions of application releases with
Ok, just reverting this to the old wording then.

2022-07-07 13:31 UTC, jonquil2002 commented on docs/vendor/releases-sharing-license-install-script.md
> +Installation commands are unique to each channel. Within each channel, there are installation commands for existing clusters and for Kubernetes installer provisioned clusters (embedded clusters).
Again, we are likely moving to provisioned. TBD in our next Style Guide meeting, but Paige and I agree that we're not happy with "-created"

2022-07-07 13:54 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
> +You can share specific versions of application releases for existing clusters or Kubernetes installer provisioned clusters. This is useful when a customer needs to install a particular version or whe
Good to know, thanks.

2022-07-07 14:24 UTC, jonquil2002 commented on docs/vendor/releases-sharing-license-install-script.md
> +  ![Existing Cluster Command](/images/embedded-cluster-command.png)
Since I'm combining them into one procedure, I'm going to use one screenshot as an example.

2022-07-07 17:41 UTC, jonquil2002 commented
@ajp-io I addressed your feedback, thanks. Pls do a final review/approval. Thanks again.

2022-07-07 18:33 UTC, ajp-io reviewed
Two small comments, but I was also wondering, this is very online installation focused since we're talking about sharing commands. Do we need to clarify that better? We have one note in one section that mentions how this isn't needed for air gap, but I wonder if we should clarify the whole section. Really all of it only applies to online, since copying the commands is all for online. Could be done separately, but that seems like a helpful clarification.

2022-07-07 18:33 UTC, ajp-io commented on docs/vendor/releases-sharing-license-install-script.md
>     installer.
I wonder if we should clarify that this command will create the cluster—it's not already created. Does this work?
```suggestion
   * Click **Embedded Cluster** to create a cluster with the Kubernetes installer and install the application on that cluster.
```

2022-07-07 20:38 UTC, jonquil2002 commented
@ajp-io I made the two small changes. Are you able to approve now?

Regarding the online installation clarification, we can do that in another card if it's really needed, I feel like that's more scope than we need to add right now. As I go through the docs, I don't see anything that tells vendors how to distribute an air gap bundle/installation. We only have Enterprise docs that explain how to install using air gap. I'm not sure if we don't have that distribution piece because maybe it's up to the vendor to decide how to distribute. Basically our docs cover online installations for the most part. So I'm not sure that we need to clarify that in this topic. If you feel we do or if you feel that we need to add information about how to distribute for air gap, would you be willing to create an SC story with some details?

2022-07-08 02:29 UTC, ajp-io approved these changes

2022-07-08 13:17 UTC, merged