Updates to gitops workflow
replicatedhq/replicated-docs pull request #545
Opened 2022-08-19 17:55 UTC by paigecalvert

Story: https://app.shortcut.com/replicated/story/55540/orange-team-document-changes-to-gitops-ux-workflow

Preview:

2022-08-19 20:12 UTC, ajp-io requested changes
There is an inaccuracy in the Path description, but I can't comment on that since this PR didn't edit that part.

2022-08-19 20:12 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +To enable pushing updates through the GitOps workflow, you must first deploy the application with Replicated using either the admin console or the kots CLI.
Maybe this is nuance that isn't worth mentioning, but you don't have to deploy. It will deploy if preflights pass, but if they fail, you don't have to deploy. The real limitation is that you have to go through an initial install flow, which will deploy the app if preflights pass.

2022-08-19 20:12 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +When you enable GitOps, the admin console sends all versions of the application, including the version that you initially deployed before GitOps was enabled, to the GitHub repository that you specify
I haven't tested this. Does it send them all, or just the most recent one?

2022-08-19 20:12 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +- A Git repository that you have read/write access permissions to.
Access and permissions feels repetitive.

2022-08-19 20:12 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +- If the repository does not have files or folders committed yet, you must commit one file by any name with simple content (such as "hello, world") so that the connection attempt succeeds with the de
I don't think we need to describe what to commit ("simple content, hello world"). They can commit anything. I'd rather say that it doesn't matter what it is, as long as something is committed. A README for the repo makes more sense than a file that says hello world, since we won't delete the hello world file, and it'll just sit there.

2022-08-19 20:12 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +    1. Select the application and the Git provider.
If you only have one app installed, you don't have to select the app.

2022-08-19 20:12 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +    1. Click **repository settings page**. On the settings page for your Git repository:
I think the name of this field is different for Bitbucket.

2022-08-19 20:12 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +       1. Enable the write access permissions for the key. This allows the admin console to push commits to the repository.
```suggestion
       1. Enable write access permissions for the key. This allows the admin console to push commits to the repository.
```

2022-08-25 15:14 UTC, paigecalvert commented on docs/enterprise/gitops-workflow.md
> +    1. Click **repository settings page**. On the settings page for your Git repository:
Does this comment refer to the name of the "repository settings page" link? Would it make sense to remove this, and just say generically: "go to the settings page for your repo"?

2022-08-25 15:22 UTC, paigecalvert commented on docs/enterprise/gitops-workflow.md
> +To enable pushing updates through the GitOps workflow, you must first deploy the application with Replicated using either the admin console or the kots CLI.
Ah, interesting, ok. I attempted a re-write. 

One thing I wasn't sure of was the last paragraph. I re-wrote to:
>If your organization has security requirements that prevent you from completing the installation workflow for the application first with the admin console or kots CLI, you cannot enable GitOps.

Is this revision more accurate, or is it best to still say "prevent you from deploying the application with the admin console or the kots CLI"? I wasn't sure if this distinction was significant in terms of which action (either following the install workflow or actually deploying) would be the gatekeeper

2022-08-25 15:25 UTC, paigecalvert commented on docs/enterprise/gitops-workflow.md
> +Subsequently, the admin console makes separate commits with any available updates that have not been deployed from the admin console.
I see what you're saying. Like, any available updates would not have be deployed from the admin console, since that's not an option with GitOps enabled. So it should go unsaid.

2022-08-25 15:25 UTC, paigecalvert commented on docs/enterprise/gitops-workflow.md
> +Subsequently, the admin console makes separate commits with any available updates that have not been deployed from the admin console.
Removed the "that have not been deployed from the admin console" part

2022-08-25 15:28 UTC, paigecalvert commented on docs/enterprise/gitops-workflow.md
> +After enabling the GitOps workflow for an application, the admin console makes your first commit with the current version that is deployed.
I re-wrote to say:
>After enabling the GitOps workflow for an application, the admin console makes your first commit with the latest available version in the admin console. The latest available version is often the current version that is deployed.

Wanted to clarify that it can be the current deployed version, since "available" might convey "not yet deployed". LMK if that makes sense to you

2022-08-25 16:30 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +    1. Click **repository settings page**. On the settings page for your Git repository:
It's account settings for Bitbucket. So I believe the link text is "account settings page" for Bitbucket. We could clarify that here or generalize the wording here a bit.

2022-08-25 16:30 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +- If the repository does not have files or folders committed yet, you must make at least one commit with any content so that the connection attempt succeeds with the deployment key when you perform t
```suggestion
- If the repository does not have files or folders committed yet, you must make at least one commit with any content so that the connection attempt succeeds with the SSH key when you perform the following task.
```

2022-08-25 16:30 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +To enable pushing updates through the GitOps workflow, you must first deploy the application with Replicated using either the admin console or the kots CLI.
I think your current wording is good. It's probably the deployment that would be the gatekeeper, but in that case you can't risk going through the installation flow because you don't know whether the preflights will pass and the app will deploy. So installation workflow seems right.

2022-08-25 16:30 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +After enabling the GitOps workflow for an application, the admin console makes your first commit with the current version that is deployed.
Yeah, that looks good.

2022-08-25 16:30 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
>  The Replicated admin console default workflow is configured to receive updates, show the changes, and deploy the updates to the cluster. You can enable a GitOps workflow instead. When using a GitOps
I can live with this, so no need for changes.

2022-08-25 16:30 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +       1. Add the public deployment key that you copied in the previous step.
```suggestion
       1. Add the SSH public key that you copied in the previous step.
```

2022-08-25 16:32 UTC, paigecalvert commented on docs/enterprise/gitops-workflow.md
> +To enable pushing updates through the GitOps workflow, you must first deploy the application with Replicated using either the admin console or the kots CLI.
Makes sense

2022-08-25 16:37 UTC, paigecalvert commented on docs/enterprise/gitops-workflow.md
> +When you enable GitOps, the admin console sends all versions of the application, including the version that you initially deployed before GitOps was enabled, to the GitHub repository that you specify
Changed the phras. "all versions" to "all updates" to fix this.

2022-08-25 16:40 UTC, paigecalvert commented on docs/enterprise/gitops-workflow.md
> +    1. Click **repository settings page**. On the settings page for your Git repository:
I generalized with:
>Go to your Git repository and open the settings page. On the settings page:

Might just help keep the docs evergreen, in case that link text changes/the git provider changes their UI/new Git providers are added. Going to resolve this, but feel free to open it back up if you have a different preference

2022-08-25 16:45 UTC, paigecalvert commented
@ajp-io I pushed a random change to the Path description so that you can more easily comment on it here, if you'd like.

2022-08-25 17:24 UTC, ajp-io commented on docs/enterprise/gitops-workflow.md
> +    1. Click **repository settings page**. On the settings page for your Git repository:
Sounds good to me.

2022-08-25 17:27 UTC, ajp-io approved these changes

2022-08-25 17:27 UTC, ajp-io commented
I'm actually just going to merge it. I want to test one thing about the path first.

2022-08-25 17:27 UTC, ajp-io commented
Or does someone from docs need to review first?

2022-08-25 17:36 UTC, merged