Update custom-resource-application.md
replicatedhq/replicated-docs pull request #596
Opened 2022-08-30 12:19 UTC by dexhorthy

2022-08-30 15:32 UTC, paigecalvert submitted a review, later dismissed
@dexhorthy, pushed some edits--take a look and feel free to merge if it looks good to you!

2022-08-30 16:56 UTC, jdewinne requested changes
I would also change the `serviceName` section to make it clear when `NodePort` can be used.

2022-08-30 16:56 UTC, jdewinne commented on docs/reference/custom-resource-application.md
>  The name of the service that has a `ClusterIP` type that should receive the traffic.
```suggestion
The name of the service that has a `ClusterIP` type or `NodePort` type if using the Kubernetes installer, that should receive the traffic.
```

2022-08-30 19:02 UTC, paigecalvert commented on docs/reference/custom-resource-application.md
>  The name of the service that has a `ClusterIP` type that should receive the traffic.
Nice 👍

2022-08-31 16:15 UTC, paigecalvert commented
@jdewinne Great suggestion--I made the change. Looks like this is blocked on your approval since you used the "changes requested" feature. Would you be able to take a look (and merge) if this looks ready to go?

2022-08-31 20:00 UTC, jdewinne approved these changes

2022-08-31 20:00 UTC, jdewinne commented
> @jdewinne Great suggestion--I made the change. Looks like this is blocked on your approval since you used the "changes requested" feature. Would you be able to take a look (and merge) if this looks ready to go?

@paigecalvert lgtm!

2022-08-31 20:27 UTC, merged

2022-08-31 20:28 UTC, paigecalvert commented
Sweet thanks @jdewinne !