56498: Replaced Redactors Example
replicatedhq/replicated-docs pull request #662
Opened 2022-09-27 18:08 UTC by jonquil2002

SC: https://app.shortcut.com/replicated/story/56498/update-example-in-the-redactor-custom-resource-topic

2022-09-27 18:35 UTC, xavpaice requested changes
this is quite an aggressive redactor - `(?P<mask>[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+)` will replace anything that is word.word.word without considering word boundaries and so on.  This would potentially redact info in logs files that is required, e.g. `cluster-resources/resources.json:    "groupVersion": "rbac.authorization.k8s.io/v1"`.

We can test the regex with a bundle that's been un-tarred:

`egrep -r '[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+' *`

2022-09-28 14:57 UTC, jonquil2002 commented
@xavpaice  Do you mean that I should replace `(?P<mask>[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+)` with this `egrep -r '[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+' *`? Or do you mean that the vendor should generate a support bundle and test the redactor ``(?P<mask>[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+)` using `egrep -r '[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+' *` to see if too much info has been redacted? If it's easier to explain by Zoom, please lmk.

2022-09-28 23:58 UTC, xavpaice commented
Unfortunatley, a host name redactor is very unlikely to be a feasible addition in this context.  While an individual could write a regex to achieve that, it would rely on the regex being a lot more specific to collect their naming convention, domain, etc. and that prevents any vendor from shipping a generic form for hostname redactor.

Perhaps what you need to complete this story is some other redactor - I'm struggling to think of some useful redactor right now that might be able to replace the redundant one, since the most generic important ones are already built in.  Perhaps someone who knows what customers are adding to their customisations would be able to chime in?

2022-09-29 04:10 UTC, xavpaice commented
can we not just copy the redactor example at the top of https://troubleshoot.sh/docs/redact/redactors/ ?

2022-09-29 19:02 UTC, jonquil2002 commented
@xavpaice  I originally copied the Troubleshoot.sh example into the Reference section when I wrote this content a few months ago, and provided a simplified version using just password in the Customize a Support Bundle procedure. But someone pointed out that password is already in the default redactors, so I was searching for a generic replacement. Since you're also having trouble finding one, I just deleted the host name example in the procedure and pointed them to the Replicated docs reference section. In the reference section, I removed the portion that redacted password.

Side note - the example on the Troubleshoot.sh site should  be updated as well by removing the password example.

Please review and approve if possible Thanks.

Thank for your help! I'll update the final version shortly.

2022-10-04 09:49 UTC, xavpaice commented on docs/reference/custom-resource-redactor.md
>  The following example shows `values`, `regex`, and `yamlPath` redaction for a support bundle:
if the example doesn't show `values` we probably should remove that from here

2022-10-04 09:50 UTC, xavpaice requested changes
one minor nit on line 70, otherwise yeah that looks great!

2022-10-04 16:27 UTC, jonquil2002 commented on docs/reference/custom-resource-redactor.md
>  The following example shows `values`, `regex`, and `yamlPath` redaction for a support bundle:
Done, thanks.

2022-10-04 16:28 UTC, jonquil2002 commented
@xavpaice @paigecalvert  Made Xav's last change. Please review/approve. Thanks.

2022-10-04 16:45 UTC, paigecalvert approved these changes
lgtm thank you!

2022-10-04 18:35 UTC, xavpaice approved these changes

2022-10-04 18:44 UTC, merged