61019: Updated Description of Replicated Components
replicatedhq/replicated-docs pull request #726
Opened 2022-10-28 15:43 UTC by jonquil2002

SC: https://app.shortcut.com/replicated/story/61019/improve-description-of-replicated-features

2022-10-28 20:51 UTC, paigecalvert commented
@jonquil2002 this is looking really good! I'm looking forward to seeing what PM thinks on the diagram. I think the only remaining Qs I have for the diagram specifically are:
- I wasn't sure what the multiple "VM" boxes around existing cluster installs & the one box for K8s installer installs represents.
- The term Kubernetes installer doesn't appear, and I think it has to do with the fact that the diagram might not convey that the app and admin console are still being installed _in_ a Kubernetes cluster _on_ a VM (right now it looks like they are just being installed directly on a VM)

And then a couple higher-level thoughts, just for your consideration:
- For the graphical user interfaces (vendor portal and admin console), screenshots could be really helpful for building initial familiarity. I'd lean towards screenshots over tables, if it becomes a decision between the two. (Especially since the info in the tables is not too complex. Could also be beneficial to pull the component names out as headings rather than rows in tables. More on that below.)
- It looks like there is not a section that describes the Kubernetes installer--was this intentional?
- Finally, thinking about the overall organization/heading names, the topic currently uses these headings: Vendor UIs, App Manager, Customer UIs. App Manager is an actual component name, while the other headings are buckets. I found this a little confusing, because it looks like the App Manager is something separate, even though it's what's powering the admin console and kots CLI.

  Maybe it would make sense to put everything under two buckets: vendor stuff versus enterprise customer stuff? Or alternatively, use the exact component names for the headings without buckets?

  Whether or not there are buckets, a benefit of using the exact component names as h2s or h3s would be having the components names appear in the right TOC.

2022-10-31 21:54 UTC, jonquil2002 commented
@paigecalvert Thanks for the great suggestions. Let's see if this works better.

@ajp-io Would appreciate your input on the diagram, and also the content could use a pass for technical accuracy. Just want to make sure I didn't make mistakes during the rewrites. Please lmk if we should pair, esp. on the diagram. I'm planning to ask the marketing team to render a better diagram once I know this reflects what PM wants to communicate. Thanks!

2022-11-14 23:00 UTC, paigecalvert reviewed
Caught a few things, and added some suggestions. Looks great! I like the idea of just listing everything under it's own heading

2022-11-14 23:00 UTC, paigecalvert commented on docs/intro-replicated.md
> +Enterprise customers can install and use the kots command-line interface (CLI) to manage and troubleshoot the application programmatically. The kots CLI interacts with the app manager and provides an
Just wasn't sure about the "troubleshoot" part of this, since downloading the support bundle requires the support-bundle kubectl plugin. Maybe "update" could work here instead?

2022-11-15 20:09 UTC, paigecalvert commented on docs/intro-replicated.md
> +To learn more about Replicated, see [Intro to Replicated: 20 Ways We Help](https://www.youtube.com/watch?v=2eOh7CofY3Q&t=779s) video.
Just noticed a typo here (missing "the")

2022-11-15 20:13 UTC, paigecalvert commented on docs/intro-replicated.md
> +- Air gapped on existing clusters or VM clusters
Does VM clusters mean Kubernetes installer provisioned clusters? (Recommend changing if so/clarifying what it means if not; I wasn't sure about the difference between "VM clusters" and "Kubernetes installer provisioned clusters" in the bullet above)

2022-11-15 20:13 UTC, paigecalvert submitted a review, later dismissed
Two small comments (had missed a typo the first pass). Looks great!

2022-11-15 20:53 UTC, ajp-io requested changes
Is Katie going to formalize the diagram?

2022-11-15 20:53 UTC, ajp-io commented on docs/intro-replicated.md
> +To learn more about Replicated, see [Intro to Replicated: 20 Ways We Help](https://www.youtube.com/watch?v=2eOh7CofY3Q&t=779s) video.
Is this link supposed to go to a specific timecode in the video? (The `t=779s` part)

2022-11-15 20:53 UTC, ajp-io commented on docs/intro-replicated.md
> +Replicated includes components and features that make it easier for you to manage and deploy applications, and for enterprise users to install and manage their application instance.
Total suggestion, take it or leave it, but this wording sounds better to me.
```suggestion
Replicated includes components and features that make it easier for you to manage and deploy applications, and for enterprise users to install and manage their instance of your application.
```

2022-11-15 20:53 UTC, ajp-io commented on docs/intro-replicated.md
> +The following diagram shows the Replicated components as they relate to you as a vendor packaging your application and the deployment to an existing cluster and a VM cluster provisioned by the Replic
I don't think "VM cluster" is the right wording here. Maybe this?
```suggestion
The following diagram shows the Replicated components as they relate to you as a vendor packaging your application and the deployment to an existing cluster and a cluster provisioned by the Replicated Kubernetes installer on a VM.
```

2022-11-15 20:53 UTC, ajp-io commented on docs/intro-replicated.md
> +You define Kubernetes manifest files, including application and custom resource manifests, using the built-in YAML editor and KOTS lint service (in the Help pane). These files describe how to distrib
I know this repo or whatever is called kots-lint, but is that a name we should use externally, especially as we move away from KOTS terminology?

2022-11-15 20:53 UTC, ajp-io commented on docs/intro-replicated.md
> +You define Kubernetes manifest files, including application and custom resource manifests, using the built-in YAML editor and KOTS lint service (in the Help pane). These files describe how to distrib
Is this talking about our custom resources or theirs?
>including application and custom resource manifests

2022-11-15 20:53 UTC, ajp-io commented on docs/intro-replicated.md
> +![YAML editor in the vendor portal](/images/yaml-editor.png)
The file selector sidebar in this image looks funny. The add file and add folder buttons are overlapping existing file names. I wonder if that's an existing bug in the vendor portal.

2022-11-15 20:53 UTC, ajp-io commented on docs/intro-replicated.md
> +![Channels](/images/channels.png)
In this picture, "Installer history" overlaps "Kubernetes Installer". Perhaps because the browser window was resized too small for it all to fit. Might want to see if we can adjust that.

2022-11-15 20:53 UTC, ajp-io commented on docs/intro-replicated.md
> +The Replicated app manager is the underlying technology that installs and manages applications on a Kubernetes cluster. It also installs the Replicated admin console and provides preflight and suppor
"also installs" isn't accurate here since the app manager is the only thing installed. This goes back to our naming conversation :) I think we should reword this to say that there is a user interface component, but I don't think we should say that it installs an admin console.

2022-11-15 20:53 UTC, ajp-io commented on docs/intro-replicated.md
> +- High availability clusters
Is this Kubernetes installer clusters that are provisioned with the `ha` flag?

2022-11-15 20:53 UTC, ajp-io commented on docs/intro-replicated.md
> +The Replicated admin console is a graphical user interface that interacts with the app manager. Enterprise customers can use the admin console to manage, update, configure, monitor, backup and restor
I wouldn't say it "interacts with the app manager", because ultimately it is the app manager. Maybe this:
```suggestion
The Replicated admin console is a graphical user interface for the app manager. Enterprise customers can use the admin console to manage, update, configure, monitor, backup and restore, and troubleshoot their application instance.
```

2022-11-15 20:53 UTC, ajp-io commented on docs/intro-replicated.md
> +The admin console is installed by the app manager.
Not really true, as I said above.

2022-11-15 20:59 UTC, ajp-io commented on docs/intro-replicated.md
> +You define Kubernetes manifest files, including application and custom resource manifests, using the built-in YAML editor and KOTS lint service (in the Help pane). These files describe how to distrib
I see we call it that here. That seems like something we should name differently IMO, though that's a separate issue from this PR. https://docs.replicated.com/reference/kots-lint#resource-requests-cpu

2022-11-15 21:36 UTC, jonquil2002 commented on docs/intro-replicated.md
> +- Air gapped on existing clusters or VM clusters
Yep, good catch. I'm just going to call it a Kubernetes installer cluster on the second mention, since that's what we've been doing elsewhere.

2022-11-15 22:44 UTC, jonquil2002 commented on docs/intro-replicated.md
> +You define Kubernetes manifest files, including application and custom resource manifests, using the built-in YAML editor and KOTS lint service (in the Help pane). These files describe how to distrib
Yes, it is Replicated CRs. Thanks for the suggestion.

2022-11-15 22:49 UTC, jonquil2002 commented on docs/intro-replicated.md
> +The Replicated admin console is a graphical user interface that interacts with the app manager. Enterprise customers can use the admin console to manage, update, configure, monitor, backup and restor
Thanks, I hesitated over that wording but couldn't find that simpler, better word :)

2022-11-15 22:55 UTC, jonquil2002 commented on docs/intro-replicated.md
> +- High availability clusters
@ajp-io  It's high availability mode with the Kubernetes installer: https://docs.replicated.com/enterprise/installing-embedded-cluster#installing-with-high-availability-mode

Is that topic impacted with the recent changes we're making to `ha`?

2022-11-15 23:21 UTC, jonquil2002 commented on docs/intro-replicated.md
> +![YAML editor in the vendor portal](/images/yaml-editor.png)
@ajp-io It does seem to be a bug in the vendor portal. I'll open an SC. It seems that no matter what size screen I use, that displays like that if there are too many files.

For this PR, I changed the screenshot to show fewer files so that the add file and add folder buttons display well.

2022-11-15 23:23 UTC, jonquil2002 commented
@ajp-io Please re-review - I incorporated all of your changes. Have a question above on the `ha` discussion.

Also, I'll ask Katie to revise the diagram in a follow-up story. We'll just go with this one for now as long as it's accurate.

2022-11-16 15:10 UTC, ajp-io commented on docs/intro-replicated.md
> +- High availability clusters
It's not impacted right now.

I wonder if we need a dedicated bullet for that. Technically that's just a Kubernetes installer provisioned cluster that's provisioned in a certain way, and it doesn't necessarily follow from the current text ("High availability clusters) that this is related to kURL.

2022-11-16 15:15 UTC, ajp-io reviewed
Couple small things. And no problem about the diagram. Just wanted to know if we were going to formalize it at some point.

2022-11-16 15:15 UTC, ajp-io commented on docs/intro-replicated.md
> +Environments include on-premises (including air gapped) and cloud hosted Kubernetes clusters. For customers who do not have an existing Kubernetes cluster, Replicated provisions a new cluster on a cu
```suggestion
Environments include on-premises (including air gapped) and cloud-hosted Kubernetes clusters. For customers who do not have an existing Kubernetes cluster, Replicated provisions a new cluster on a customer's virtual machine (VM), where the application is then installed.
```

2022-11-16 15:15 UTC, ajp-io commented on docs/intro-replicated.md
> +The following diagram shows the Replicated components as they relate to you as a vendor packaging your application and the deployment to an existing cluster and a cluster provisioned by the Replicate
```suggestion
The following diagram shows the Replicated components as they relate to you as a vendor packaging your application, and the deployment to an existing cluster and a cluster provisioned by the Replicated Kubernetes installer on a VM.
```

2022-11-16 15:15 UTC, ajp-io commented on docs/intro-replicated.md
> +### Admin Console
Maybe this should come right after App Manager instead of having Kubernetes Installer sandwiched between them.

2022-11-16 15:15 UTC, ajp-io commented on docs/intro-replicated.md
> +
This is in the above paragraph already.
```suggestion
```

2022-11-16 16:12 UTC, jonquil2002 commented on docs/intro-replicated.md
> +- High availability clusters
I can remove that bullet. Originally, I was wondering whether or not it was needed in this context.

2022-11-16 16:42 UTC, jonquil2002 commented
@ajp-io @paigecalvert  Made Alex's last changes. Please review/approve if possible. Thanks.

2022-11-16 16:51 UTC, paigecalvert approved these changes

2022-11-16 18:25 UTC, ajp-io approved these changes

2022-11-16 18:32 UTC, merged