DRAFT: 64052-New: Modular and Discoverability New PR
replicatedhq/replicated-docs pull request #847
Opened 2022-12-20 22:49 UTC by jonquil2002

SC: https://app.shortcut.com/replicated/story/64052/review-prs-for-troubleshoot-with-multiple-specs

This will end up being the replacement PR for the one I started here: https://github.com/replicatedhq/replicated-docs/pull/843   I'll close the old one when I'm ready.

This new PR lets me keep a Diff for review.

2022-12-22 00:35 UTC, paigecalvert reviewed
@jonquil2002 Reading through this was super helpful, thanks--it raised some questions for me about the usage on the enterprise side, and the strategy on the vendor side, which I tried to articulate in comments. I don't think I succeeded in being very concise, so LMK if you'd like to talk through any of these tomorrow

2022-12-22 00:35 UTC, paigecalvert commented on docs/enterprise/troubleshooting-an-app.md
> +  ```
Same comment as above, where I wonder if it would make sense to have a single section (maybe something like "Generate a Single Support Bundle from Multiple Specs") that describes why you'd need to do this, and then provides usage details for the `support-bundle` command, including the `--load-cluster-specs` option, plus some examples. This topic section in the troubleshoot docs has some details about the usage of the load-cluster-specs flag: https://troubleshoot.sh/docs/support-bundle/discover-cluster-specs/#usage

2022-12-22 00:35 UTC, paigecalvert commented on docs/vendor/support-modular-support-bundle-specs.md
> +For example, in an application that ships MySQL, NGINX, and Redis:
I see the balance you are striking here of procedure versus example. It feels like the combination of formatting might make this more challenging to parse.

One idea that comes to mind is that I could see the logic in converting this topic into something more conceptual that focuses on the methodology of the modular approach to writing support bundles. Something like: 
```
About Creating Modular Support Bundles
  Overview of Modular Support Bundles (benefits, options, how users have a command to consolidate them)
  Examples
    Create Support Bundle Specs Per Component
    Create Support Bundle Specs in Secrets 
```
The benefit here could be that it's more describing an approach to organizing the support bundle specifications, rather than the heavy procedural content of actually creating the specs themselves

2022-12-22 00:35 UTC, paigecalvert commented on docs/vendor/support-modular-support-bundle-specs.md
> +1. Add a support bundle specification to a cluster as `Kind: Secret`. Add the label `troubleshoot.io/kind: supportbundle` and a `data` key matching `support-bundle-spec`.
I'm seeing that the troubleshoot docs for discovering multiple specs mention that the specs can be added to Secrets _or_ ConfigMaps, whereas this topic suggests it's just Secrets. Here's the troubleshoot topic I'm looking at: https://troubleshoot.sh/docs/support-bundle/discover-cluster-specs

(could be something else to run by Ada)

2022-12-22 14:47 UTC, jonquil2002 commented on docs/vendor/support-modular-support-bundle-specs.md
> +For example, in an application that ships MySQL, NGINX, and Redis:
Thanks you!!!

2022-12-22 17:31 UTC, paigecalvert reviewed
Thanks @jonquil2002 -- just added some questions that came up for me about this feature as well while reading through!

2022-12-22 17:31 UTC, paigecalvert commented on docs/vendor/support-online-support-bundle-specs.md
> +Including a self-link to a source repository helps to ensure that the latest online specification is available to your support bundle. In turn, the support bundle proactively detects potential proble
I think the self-link terminology tripped me up a bit as well. Is "Including a self-link to a source repository" that same thing as including the URI field, or something different? Is it just describing what type format the URI should be?

Maybe there's a segue between these two paragraphs that explains what the self-link is referring to?

2022-12-22 17:31 UTC, paigecalvert commented on docs/vendor/support-online-support-bundle-specs.md
> +Including a self-link to a source repository helps to ensure that the latest online specification is available to your support bundle. In turn, the support bundle proactively detects potential proble
I was also curious reading the intro: how does this related to the modular approach? Maybe another method for going about that as well? For example, could people write a bunch of specs and then make them accessible online? 

I also noticed that the `support-bundle` command accepts a URL as an argument. Is that referring to this format? As if, if a vendor used a modular approach and had all the specs available online, would their end user be able to list out two+ URLs in the `support-bundle` URL to generate a single archive?

2022-12-22 17:31 UTC, paigecalvert commented on docs/vendor/support-online-support-bundle-specs.md
> +**Example:**
It almost seemed like it could be helpful to have a visual of what this looks like higher up as part of the overview description. I found that I wanted to scroll down to see the YAML while I was reading that

2022-12-22 17:31 UTC, paigecalvert commented on docs/vendor/support-online-support-bundle-specs.md
> +With the addition of the `uri:` property, the support bundle gets the latest specification if it can, or falls back to the earlier release.  For a complete example, see [Debugging Kubernetes: Enhance
Just realizing this...Should we add this in the Support Bundle Reference topic? Since it's a new `uri:` field, it seems like it could fit well there as space to describe what it is and how to use it/the requirements/ the type of URI it accepts

2022-12-22 21:31 UTC, jonquil2002 commented on docs/vendor/support-online-support-bundle-specs.md
> +With the addition of the `uri:` property, the support bundle gets the latest specification if it can, or falls back to the earlier release.  For a complete example, see [Debugging Kubernetes: Enhance
Good suggestion. I took a look at the schema and this is at the properties level. We don't document the properties in the Reference section, only the global fields.

I noticed that the `uri` field at the properties levels also seems to support hosting the preflights specification online, which Ada alluded to in one place in this doc.

2022-12-22 21:47 UTC, jonquil2002 commented on docs/vendor/support-online-support-bundle-specs.md
> +**Example:**
The contents of this YAML contain the `uri` field populated with a raw URL, so it can't be show earlier. The earlier YAML is supported to be v1, without the `uri` field. But hopefully I made the wording clearer now.

2022-12-23 15:21 UTC, jonquil2002 commented on docs/vendor/support-modular-support-bundle-specs.md
> +## Add Discoverability to Clusters
We talked about the details of this yesterday, I think this is resolved.

2022-12-23 15:22 UTC, jonquil2002 commented on docs/vendor/support-modular-support-bundle-specs.md
> +1. Add a support bundle specification to a cluster as `Kind: Secret`. Add the label `troubleshoot.io/kind: supportbundle` and a `data` key matching `support-bundle-spec`.
I added a clarification about the two options (Secrets and ConfigMaps).

2022-12-23 16:01 UTC, jonquil2002 commented on docs/vendor/support-online-support-bundle-specs.md
> +Including a self-link to a source repository helps to ensure that the latest online specification is available to your support bundle. In turn, the support bundle proactively detects potential proble
Yep, updated the docs to say multiple online specs are supported with modular design.

2022-12-23 16:01 UTC, jonquil2002 commented on docs/enterprise/troubleshooting-an-app.md
> +Do one of the following:
Thanks - incorporated your suggestions.

2022-12-23 19:13 UTC, paigecalvert reviewed
Overall the format/organization is looking good @jonquil2002 -- I mainly focused on some remaining technical questions that are coming up for me. I think adding additional the additional context from these questions to each area of the feature could help make it easier to understand

2022-12-23 19:13 UTC, paigecalvert commented on docs/vendor/support-modular-support-bundle-specs.md
> +Custom resource definitions (CRDs) are not available for support bundles or preflights, so they must be wrapped in a Secret. For more information about adding Secrets, see [Support Bundle specs to a
>Custom resource definitions (CRDs) are not available for support bundles or preflights, so they must be wrapped in a Secret.

What does this mean? I think more info from Ada could be useful. It sounds like it's providing some background about why you would be adding the spec to a Secret or ConfigMap rather than creating a separate CRD, but might need a bit more context to make this clear

2022-12-23 19:13 UTC, paigecalvert commented on docs/vendor/support-modular-support-bundle-specs.md
>  ```shell
Should remove "shell" from these. it doesn't do anything

2022-12-23 19:13 UTC, paigecalvert commented on docs/vendor/support-modular-support-bundle-specs.md
>  ```
Just noting the question we had for Ada about why someone would manually type out the Secrets rather than using --load-cluster-specs in this case. (Could be useful to demonstrate that that is an option for end users)

2022-12-23 19:13 UTC, paigecalvert commented on docs/vendor/support-modular-support-bundle-specs.md
> + For real use cases, see the [troubleshoot-specs repo](https://github.com/replicatedhq/troubleshoot-specs) on GitHub.
Recommend expanding on what "real use cases" means if possible. It almost negates the examples here. Maybe examples of what this means and why someone would want to go look at those use cases?

2022-12-23 19:13 UTC, paigecalvert commented on docs/vendor/support-online-support-bundle-specs.md
> +You can make the definition of one or more support bundle specifications available online. The schema supports a `uri://` field that, when set, causes the support bundle to use the online specificati
I think I still don't understand the difference between the online spec and the "original spec". Are you supposed to be saving an "original spec" somewhere else as well if you are hosting one online?

The other question that comes up for me is around "any additional collectors or analyzers". That makes it sound like the collectors are analyzers that are used as a fallback are _different_ from the ones in the online spec?

I think some examples might be useful here. I don't really understand what's going on with the original/fallback stuff, and if the vendor has to take any action to make sure that's set up properly

2022-12-23 19:13 UTC, paigecalvert commented on docs/vendor/support-online-support-bundle-specs.md
> +Including a self-link to an source repository helps to ensure that the latest online specification is available to your support bundle. In turn, the support bundle proactively detects potential probl
How does keeping it online "ensure that the latest online specification is available to your support bundle."? Is the idea that it's easier for a team to be updating a support bundle in a github repo rather than one in the vendor portal?

Additionally, how does an online support bundle "proactively detect potential problems"? 

(Questions for Ada of course. Adding in these details I think will make it easier to convey the value statement of this feature)

2022-12-23 19:13 UTC, paigecalvert commented on docs/vendor/support-online-support-bundle-specs.md
> +You can make the definition of one or more support bundle specifications available online. The schema supports a `uri://` field that, when set, causes the support bundle to use the online specificati
Reading below, it looks like it falls back to a previous release? What if the vendor doesn't have a previous release?

2022-12-28 16:24 UTC, jonquil2002 commented on docs/enterprise/troubleshooting-an-app.md
> +- Two URLs and a support bundle manifest
Yep, I'll ask Ada to review that section carefully. It raises more questions for me, I won't be surprised if some of it should not be customer facing right now. Perhaps some of it will end up as guidance in the vendor section.

2022-12-29 16:18 UTC, jonquil2002 commented on docs/vendor/support-modular-support-bundle-specs.md
>  ```
@adamancini Can you give us an idea why a vendor would want to run `kubectl get secrets` with the label instead of just using `--load-cluster-specs`?

@paigecalvert  The `--load-cluster-specs` example was there but then we decided it should be in the Enterprise section and point vendors to that with an x-ref.

2022-12-29 16:19 UTC, jonquil2002 commented on docs/vendor/support-modular-support-bundle-specs.md
> + For real use cases, see the [troubleshoot-specs repo](https://github.com/replicatedhq/troubleshoot-specs) on GitHub.
@adamancini  Can you expand on the real use cases - what value do they present versus the example here? Please see Paige's questions above.

2022-12-29 16:21 UTC, jonquil2002 commented on docs/vendor/support-online-support-bundle-specs.md
> +You can make the definition of one or more support bundle specifications available online. The schema supports a `uri://` field that, when set, causes the support bundle to use the online specificati
@adamancini If possible, let's pair about this and the next question about previous releases, fall back, etc. It's not clear to either Paige or myself and I feel like some further explanation might be needed in the docs.

2022-12-29 16:21 UTC, jonquil2002 commented on docs/vendor/support-online-support-bundle-specs.md
> +Including a self-link to an source repository helps to ensure that the latest online specification is available to your support bundle. In turn, the support bundle proactively detects potential probl
@adamancini If needed let's pair on this one if it can't be easily answered here. Thanks.

2022-12-29 19:01 UTC, jonquil2002 commented on docs/vendor/support-online-support-bundle-specs.md
> +Including a self-link to an source repository helps to ensure that the latest online specification is available to your support bundle. In turn, the support bundle proactively detects potential probl
Answered :)

2022-12-29 19:02 UTC, jonquil2002 commented on docs/vendor/support-online-support-bundle-specs.md
> +You can make the definition of one or more support bundle specifications available online. The schema supports a `uri://` field that, when set, causes the support bundle to use the online specificati
Answered :)

2022-12-29 21:43 UTC, jonquil2002 commented on docs/vendor/support-modular-support-bundle-specs.md
> +Custom resource definitions (CRDs) are not available for support bundles or preflights, so they must be wrapped in a Secret. For more information about adding Secrets, see [Support Bundle specs to a
@adamancini I don't think that we need to mention the CRDs here, unless a vendor would be expecting a CRD? Is there is more context that you can add?

2022-12-29 21:49 UTC, jonquil2002 commented on docs/vendor/support-online-support-bundle-specs.md
> +The `uri` field is added to the specification as a raw file link. Replicated hosts the online specification on [GitHub](https://github.com/replicatedhq/troubleshoot-specs/blob/main/in-cluster/ekco.ya
@adamancini In this example, wouldn't the URI field need to be added to the spec in the cluster so it would know to look online first? If so, wouldn't that mean that the customer would need to upgrade the application first to get the updated spec into the cluster?

I know you want the online spec to link to itself, but the spec in the cluster - in this example - won't know to use the URI unless the cluster spec is updated via an application upgrade. Yes?

2023-01-04 16:51 UTC, adamancini requested changes
2 small nits and otherwise lgtm!

2023-01-04 16:51 UTC, adamancini commented on docs/vendor/support-online-support-bundle-specs.md
> +The `uri` field is added to the specification as a raw file link. Replicated hosts the online specification on [GitHub](https://github.com/replicatedhq/troubleshoot-specs/blob/main/in-cluster/ekco.ya
that's correct, at this "stage" of the install, if version 1 did not have the URI in it, and version 2 does, then the user would need to upgrade to at least version 2 to get future updates from the URI.

I think the point I was trying to make is that the earlier you get this URI field added to your spec, the better.

2023-01-04 16:51 UTC, adamancini commented on docs/enterprise/troubleshooting-an-app.md
> +The `--load-cluster-specs` flag can be combined with multiple specifications, such as URLs or specifications that match a custom label. For more information, see [Discover Cluster Specs](https://trou
great! lgtm

2023-01-04 16:51 UTC, adamancini commented on docs/vendor/support-modular-support-bundle-specs.md
> +You can create separate manifest files or use a combination of manifest files, URLs, and Kubernetes Secrets or ConfigMaps. Then, customers can use the support-bundle CLI to generate a merged support
great!

2023-01-04 16:51 UTC, adamancini commented on docs/vendor/support-modular-support-bundle-specs.md
> +     - logs:
I think an extra space got added here

2023-01-04 16:51 UTC, adamancini commented on docs/vendor/support-modular-support-bundle-specs.md
> +This collector and analyzer checks that the default password is used for Redis:
This collector checks if a Redis server is up and responding/active and gets version info - the password is just required in order for the collector to talk to the server.
https://troubleshoot.sh/docs/collect/redis/#included-resources

2023-01-04 16:51 UTC, adamancini commented on docs/vendor/support-modular-support-bundle-specs.md
> +Custom resource definitions (CRDs) are not available for support bundles or preflights, so they must be wrapped in a Secret. For more information about adding Secrets, see [Support Bundle specs to a
Our support bundle specs _look_ like CRDs.  if you look at a spec file, it seems that you should just be able to `kubectl create support-bundle` or `kubectl get support-bundles` but there's no `support-bundle` resource - we started discussion on this https://github.com/replicatedhq/troubleshoot/issues/664 here and decided that we would not do it for now

2023-01-05 17:39 UTC, paigecalvert submitted a review, later dismissed
Just a few minor comments! I think the only one that's a "blocker" though is making sure the Configuring topic appears in only one place in the TOC

Looks great!!

2023-01-05 17:39 UTC, paigecalvert commented on sidebars.js
> +              'vendor/preflight-support-bundle-creating',
Reminder to remove the old reference to the `vendor/preflight-support-bundle-creating` topic in the sidebar before merging!

I'm still seeing it under packaging in the preview:
<img width="161" alt="Screen Shot 2023-01-05 at 10 26 54 AM" src="https://user-images.githubusercontent.com/11523028/210842944-220d4796-2446-40bd-9b2d-6b1d13d6d063.png">

2023-01-05 17:39 UTC, paigecalvert commented on docs/vendor/support-modular-support-bundle-specs.md
> +To make support bundle specifications discoverable in a cluster, you must wrap them in a Secret. You add a specification as `Kind: Secret` and include the label `troubleshoot.io/kind: supportbundle`
> To make support bundle specifications discoverable in a cluster, you must wrap them in a Secret.

Should this say "Secret or ConfigMap"? (There could then be another sentence to clarify that this example shows using a Secret)

2023-01-05 17:39 UTC, paigecalvert commented on docs/vendor/support-modular-support-bundle-specs.md
> +[`kURL/addons/flannel/template/yaml/troubleshoot.yaml`](https://github.com/adamancini/kURL/blob/main/addons/flannel/template/base/yaml/troubleshoot.yaml)
It looks like this is pointing to a YAML file in Ada's github. As someone looking at this without context, I'm not sure why the link is here, or what I would be expected to use the YAML file for.

To spell out more clearly why I would follow this link, recommend editing this to use our xref format: "For an example Secret that includes collector and analyzer specifications, see ... " Or even more detailed: "The following example shows using online collector and analyzers specifications. For an example Secret that includes collector and analyzer specifications in the manifest file itself..."

2023-01-05 17:39 UTC, paigecalvert commented on docs/vendor/support-online-support-bundle-specs.md
> +If you are using a modular approach to designing support bundles, you can use multiple online specifications. Each specification supports one  URI link. For more information about modular specificati
Extra space here I think: "one  URI link"

2023-01-05 20:06 UTC, jonquil2002 commented on docs/vendor/support-modular-support-bundle-specs.md
> +[`kURL/addons/flannel/template/yaml/troubleshoot.yaml`](https://github.com/adamancini/kURL/blob/main/addons/flannel/template/base/yaml/troubleshoot.yaml)
Good idea, thanks.

2023-01-05 20:13 UTC, paigecalvert approved these changes

2023-01-06 20:16 UTC, merged