IMPORTANT: Add note to recommend those that has ubuntu distro do not use this release
replicatedhq/replicated-docs pull request #886
Opened 2023-01-13 17:26 UTC by camilamacedo86

IMPORTANT: Add note to recommend those that has ubuntu distro do not use this release

2023-01-13 17:28 UTC, camilamacedo86 commented on docs/release-notes/rn-kubernetes-installer.md
> +We recommend use `v2023.01.13-1` instead because a regression issue was identified on this release where if conflicts resolutions are faced to install the host packages then the package manager might
```suggestion
We recommend use `v2023.01.13-1` instead because a regression issue was identified on this release where if conflicts resolutions are faced to install the host packages then the package manager might remove host one ore more packages installed (valid only for ubuntu distributions). In the best scenarios the packaged removed might not affected the host or it can be sorted out by getting the package re-installed with `sudo apt-get install <package>`. In the worst scenarios it might can remove important host packages such as `openssh` which would no longer allow you be able to connect via ssh in the host.  
```

2023-01-13 17:36 UTC, chris-sanders requested changes

2023-01-13 17:36 UTC, chris-sanders commented on docs/release-notes/rn-kubernetes-installer.md
> +We recommend use `v2023.01.13-1` instead because a regression issue was identified on this release where if conflicts resolutions are faced to install the host packages then the package manager might
```suggestion
A regression that can unintentionally remove critical system packages from Ubuntu machines has been found in this versions. Version `v2023.01.13-1` includes a fix for this regression and should be used in all cases instead. 
```

2023-01-13 17:36 UTC, chris-sanders commented on docs/release-notes/rn-kubernetes-installer.md
> +We recommend use `v2023.01.13-1` instead because a regression issue was identified on this release where if conflicts resolutions are faced to install the host packages then the package manager might
Suggested reworking

2023-01-13 18:21 UTC, laverya commented on docs/release-notes/rn-kubernetes-installer.md
> +We recommend use `v2023.01.13-1` instead because a regression issue was identified on this release where if conflicts resolutions are faced to install the host packages then the package manager might
I would say 'in this version.' instead of 'in this versions.', if that makes sense

2023-01-13 21:57 UTC, camilamacedo86 commented on docs/release-notes/rn-kubernetes-installer.md
> +We recommend use `v2023.01.13-1` instead because a regression issue was identified on this release where if conflicts resolutions are faced to install the host packages then the package manager might
@paigecalvert @laverya @chris-sanders,

I think the most important Is we have the info. Please, feel free to pick the best wording word and move forward with this one. I am OK with all suggestions.

2023-01-14 16:49 UTC, emosbaugh approved these changes

2023-01-17 16:12 UTC, paigecalvert approved these changes

2023-01-17 17:58 UTC, merged

2023-01-17 17:59 UTC, camilamacedo86 commented
We got the OK in the chat. Thank you for all help.